#pragma once
/* chasm_rl_shim.h — maps chasm_*(ctx, ...) calls to rl_*(...) functions.
   The self-hosted codegen emits chasm_<funcname>(ctx, args). For raylib
   bindings the codegen doesn't know the extern mapping, so we bridge here.
   
   Using inline functions instead of macros to avoid conflicts with forward
   declarations generated by the Chasm compiler. */
#include "chasm_rl.h"

/* ---- Window / system ------------------------------------------------------- */
static inline int64_t chasm_screen_w(ChasmCtx *ctx)                    { (void)ctx; return rl_screen_width(); }
static inline int64_t chasm_screen_h(ChasmCtx *ctx)                    { (void)ctx; return rl_screen_height(); }
static inline void    chasm_set_fps(ChasmCtx *ctx, int64_t fps)        { (void)ctx; rl_set_target_fps(fps); }
static inline void    chasm_set_title(ChasmCtx *ctx, const char *t)    { (void)ctx; rl_set_window_title(t); }
static inline int64_t chasm_fps(ChasmCtx *ctx)                         { (void)ctx; return rl_fps(); }
static inline double  chasm_dt(ChasmCtx *ctx)                          { (void)ctx; return rl_frame_time(); }
static inline double  chasm_time(ChasmCtx *ctx)                        { (void)ctx; return rl_time(); }

/* ---- Drawing --------------------------------------------------------------- */
static inline void chasm_clear(ChasmCtx *ctx, int64_t c)               { (void)ctx; rl_clear_background(c); }
static inline void chasm_draw_rect(ChasmCtx *ctx, double x, double y, double w, double h, int64_t c)
    { (void)ctx; rl_draw_rectangle(x, y, w, h, c); }
static inline void chasm_draw_rect_lines(ChasmCtx *ctx, double x, double y, double w, double h, int64_t c)
    { (void)ctx; rl_draw_rectangle_lines(x, y, w, h, c); }
static inline void chasm_draw_rect_rounded(ChasmCtx *ctx, double x, double y, double w, double h, double r, int64_t s, int64_t c)
    { (void)ctx; rl_draw_rectangle_rounded(x, y, w, h, r, s, c); }
static inline void chasm_draw_circle(ChasmCtx *ctx, double x, double y, double r, int64_t c)
    { (void)ctx; rl_draw_circle(x, y, r, c); }
static inline void chasm_draw_circle_lines(ChasmCtx *ctx, double x, double y, double r, int64_t c)
    { (void)ctx; rl_draw_circle_lines(x, y, r, c); }
static inline void chasm_draw_line(ChasmCtx *ctx, double x1, double y1, double x2, double y2, int64_t c)
    { (void)ctx; rl_draw_line(x1, y1, x2, y2, c); }
static inline void chasm_draw_line_ex(ChasmCtx *ctx, double x1, double y1, double x2, double y2, double t, int64_t c)
    { (void)ctx; rl_draw_line_ex(x1, y1, x2, y2, t, c); }
static inline void chasm_draw_text(ChasmCtx *ctx, const char *text, double x, double y, int64_t sz, int64_t c)
    { (void)ctx; rl_draw_text(text, x, y, sz, c); }
static inline double chasm_measure_text(ChasmCtx *ctx, const char *text, int64_t sz)
    { (void)ctx; return rl_measure_text(text, sz); }
static inline void chasm_draw_fps(ChasmCtx *ctx, double x, double y)
    { (void)ctx; rl_draw_fps(x, y); }

/* ---- Texture --------------------------------------------------------------- */
static inline int64_t chasm_load_texture(ChasmCtx *ctx, const char *p)
    { (void)ctx; return rl_load_texture(p); }
static inline void chasm_unload_texture(ChasmCtx *ctx, int64_t h)
    { (void)ctx; rl_unload_texture(h); }
static inline void chasm_draw_texture(ChasmCtx *ctx, int64_t h, double x, double y, int64_t t)
    { (void)ctx; rl_draw_texture(h, x, y, t); }
static inline void chasm_draw_texture_ex(ChasmCtx *ctx, int64_t h, double x, double y, double r, double s, int64_t t)
    { (void)ctx; rl_draw_texture_ex(h, x, y, r, s, t); }
static inline void chasm_draw_texture_rect(ChasmCtx *ctx, int64_t h, double sx, double sy, double sw, double sh, double dx, double dy, int64_t t)
    { (void)ctx; rl_draw_texture_rec(h, sx, sy, sw, sh, dx, dy, t); }
static inline int64_t chasm_texture_w(ChasmCtx *ctx, int64_t h)
    { (void)ctx; return rl_texture_width(h); }
static inline int64_t chasm_texture_h(ChasmCtx *ctx, int64_t h)
    { (void)ctx; return rl_texture_height(h); }

/* ---- Font ------------------------------------------------------------------ */
static inline int64_t chasm_load_font(ChasmCtx *ctx, const char *p)
    { (void)ctx; return rl_load_font(p); }
static inline void chasm_draw_text_ex(ChasmCtx *ctx, int64_t f, const char *t, double x, double y, double sz, double sp, int64_t c)
    { (void)ctx; rl_draw_text_ex(f, t, x, y, sz, sp, c); }

/* ---- Audio ----------------------------------------------------------------- */
static inline void    chasm_init_audio(ChasmCtx *ctx)                  { (void)ctx; rl_init_audio(); }
static inline void    chasm_close_audio(ChasmCtx *ctx)                 { (void)ctx; rl_close_audio(); }
static inline int64_t chasm_load_sound(ChasmCtx *ctx, const char *p)   { (void)ctx; return rl_load_sound(p); }
static inline void    chasm_play_sound(ChasmCtx *ctx, int64_t h)       { (void)ctx; rl_play_sound(h); }
static inline void    chasm_stop_sound(ChasmCtx *ctx, int64_t h)       { (void)ctx; rl_stop_sound(h); }
static inline int64_t chasm_load_music(ChasmCtx *ctx, const char *p)   { (void)ctx; return rl_load_music(p); }
static inline void    chasm_play_music(ChasmCtx *ctx, int64_t h)       { (void)ctx; rl_play_music(h); }
static inline void    chasm_update_music(ChasmCtx *ctx, int64_t h)     { (void)ctx; rl_update_music(h); }
static inline void    chasm_stop_music(ChasmCtx *ctx, int64_t h)       { (void)ctx; rl_stop_music(h); }

/* ---- Keyboard -------------------------------------------------------------- */
static inline bool    chasm_key_down(ChasmCtx *ctx, int64_t k)         { (void)ctx; return rl_is_key_down(k); }
static inline bool    chasm_key_pressed(ChasmCtx *ctx, int64_t k)      { (void)ctx; return rl_is_key_pressed(k); }
static inline bool    chasm_key_released(ChasmCtx *ctx, int64_t k)     { (void)ctx; return rl_is_key_released(k); }
static inline bool    chasm_key_up(ChasmCtx *ctx, int64_t k)           { (void)ctx; return rl_is_key_up(k); }
static inline int64_t chasm_key_last(ChasmCtx *ctx)                    { (void)ctx; return rl_get_key_pressed(); }

/* ---- Mouse ----------------------------------------------------------------- */
static inline double chasm_mouse_x(ChasmCtx *ctx)                      { (void)ctx; return rl_mouse_x(); }
static inline double chasm_mouse_y(ChasmCtx *ctx)                      { (void)ctx; return rl_mouse_y(); }
static inline double chasm_mouse_dx(ChasmCtx *ctx)                     { (void)ctx; return rl_mouse_delta_x(); }
static inline double chasm_mouse_dy(ChasmCtx *ctx)                     { (void)ctx; return rl_mouse_delta_y(); }
static inline bool   chasm_mouse_down(ChasmCtx *ctx, int64_t b)        { (void)ctx; return rl_is_mouse_down(b); }
static inline bool   chasm_mouse_pressed(ChasmCtx *ctx, int64_t b)     { (void)ctx; return rl_is_mouse_pressed(b); }
static inline bool   chasm_mouse_released(ChasmCtx *ctx, int64_t b)    { (void)ctx; return rl_is_mouse_released(b); }
static inline double chasm_mouse_wheel(ChasmCtx *ctx)                  { (void)ctx; return rl_mouse_wheel(); }
static inline void   chasm_hide_cursor(ChasmCtx *ctx)                  { (void)ctx; rl_hide_cursor(); }
static inline void   chasm_show_cursor(ChasmCtx *ctx)                  { (void)ctx; rl_show_cursor(); }

/* ---- Audio extended -------------------------------------------------------- */
static inline bool   chasm_sound_playing(ChasmCtx *ctx, int64_t h)              { (void)ctx; return rl_sound_playing(h); }
static inline void   chasm_sound_volume(ChasmCtx *ctx, int64_t h, double vol)   { (void)ctx; rl_sound_volume(h, vol); }
static inline void   chasm_sound_pitch(ChasmCtx *ctx, int64_t h, double pitch)  { (void)ctx; rl_sound_pitch(h, pitch); }
static inline void   chasm_pause_sound(ChasmCtx *ctx, int64_t h)                { (void)ctx; rl_pause_sound(h); }
static inline void   chasm_resume_sound(ChasmCtx *ctx, int64_t h)               { (void)ctx; rl_resume_sound(h); }
static inline bool   chasm_music_playing(ChasmCtx *ctx, int64_t h)              { (void)ctx; return rl_music_playing(h); }
static inline void   chasm_music_volume(ChasmCtx *ctx, int64_t h, double vol)   { (void)ctx; rl_music_volume(h, vol); }
static inline void   chasm_music_pitch(ChasmCtx *ctx, int64_t h, double pitch)  { (void)ctx; rl_music_pitch(h, pitch); }
static inline double chasm_music_length(ChasmCtx *ctx, int64_t h)               { (void)ctx; return rl_music_length(h); }
static inline double chasm_music_played(ChasmCtx *ctx, int64_t h)               { (void)ctx; return rl_music_played(h); }
static inline void   chasm_pause_music(ChasmCtx *ctx, int64_t h)                { (void)ctx; rl_pause_music(h); }
static inline void   chasm_resume_music(ChasmCtx *ctx, int64_t h)               { (void)ctx; rl_resume_music(h); }

/* ---- Window extended ------------------------------------------------------- */
static inline bool  chasm_window_resized(ChasmCtx *ctx)                         { (void)ctx; return rl_window_resized(); }
static inline void  chasm_set_window_size(ChasmCtx *ctx, int64_t w, int64_t h)  { (void)ctx; rl_set_window_size(w, h); }
static inline void  chasm_toggle_fullscreen(ChasmCtx *ctx)                      { (void)ctx; rl_toggle_fullscreen(); }
static inline bool  chasm_is_fullscreen(ChasmCtx *ctx)                          { (void)ctx; return rl_is_fullscreen(); }
static inline bool  chasm_window_focused(ChasmCtx *ctx)                         { (void)ctx; return rl_window_focused(); }

/* ---- Drawing extended ------------------------------------------------------ */
static inline void chasm_draw_triangle(ChasmCtx *ctx, double x1, double y1, double x2, double y2, double x3, double y3, int64_t c)
    { (void)ctx; rl_draw_triangle(x1, y1, x2, y2, x3, y3, c); }
static inline void chasm_draw_triangle_lines(ChasmCtx *ctx, double x1, double y1, double x2, double y2, double x3, double y3, int64_t c)
    { (void)ctx; rl_draw_triangle_lines(x1, y1, x2, y2, x3, y3, c); }
static inline void chasm_draw_ellipse(ChasmCtx *ctx, double cx, double cy, double rx, double ry, int64_t c)
    { (void)ctx; rl_draw_ellipse(cx, cy, rx, ry, c); }
static inline void chasm_draw_ring(ChasmCtx *ctx, double cx, double cy, double inner, double outer, double start, double end, int64_t segs, int64_t c)
    { (void)ctx; rl_draw_ring(cx, cy, inner, outer, start, end, segs, c); }
static inline void chasm_draw_poly(ChasmCtx *ctx, double cx, double cy, int64_t sides, double radius, double rot, int64_t c)
    { (void)ctx; rl_draw_poly(cx, cy, sides, radius, rot, c); }

/* ---- Texture extended ------------------------------------------------------ */
static inline void chasm_draw_texture_tiled(ChasmCtx *ctx, int64_t h, double sx, double sy, double sw, double sh, double dx, double dy, double dw, double dh, int64_t tint)
    { (void)ctx; rl_draw_texture_tiled(h, sx, sy, sw, sh, dx, dy, dw, dh, tint); }
static inline void chasm_set_texture_filter(ChasmCtx *ctx, int64_t h, int64_t filter)
    { (void)ctx; rl_set_texture_filter(h, filter); }

/* ---- Camera 2D ------------------------------------------------------------- */
static inline void   chasm_camera2d_begin(ChasmCtx *ctx, double cx, double cy, double tx, double ty, double rot, double zoom)
    { (void)ctx; rl_camera2d_begin(cx, cy, tx, ty, rot, zoom); }
static inline void   chasm_camera2d_end(ChasmCtx *ctx)
    { (void)ctx; rl_camera2d_end(); }
static inline double chasm_world_to_screen_x(ChasmCtx *ctx, double wx, double wy, double cx, double cy, double tx, double ty, double rot, double zoom)
    { (void)ctx; return rl_world_to_screen_x(wx, wy, cx, cy, tx, ty, rot, zoom); }
static inline double chasm_world_to_screen_y(ChasmCtx *ctx, double wx, double wy, double cx, double cy, double tx, double ty, double rot, double zoom)
    { (void)ctx; return rl_world_to_screen_y(wx, wy, cx, cy, tx, ty, rot, zoom); }

/* ---- Gamepad --------------------------------------------------------------- */
static inline bool   chasm_gamepad_available(ChasmCtx *ctx, int64_t pad)               { (void)ctx; return rl_gamepad_available(pad); }
static inline bool   chasm_gamepad_button_down(ChasmCtx *ctx, int64_t pad, int64_t btn){ (void)ctx; return rl_gamepad_button_down(pad, btn); }
static inline bool   chasm_gamepad_button_pressed(ChasmCtx *ctx, int64_t pad, int64_t btn){ (void)ctx; return rl_gamepad_button_pressed(pad, btn); }
static inline double chasm_gamepad_axis(ChasmCtx *ctx, int64_t pad, int64_t axis)      { (void)ctx; return rl_gamepad_axis(pad, axis); }

/* ---- Mouse extended -------------------------------------------------------- */
static inline void chasm_set_mouse_pos(ChasmCtx *ctx, double x, double y) { (void)ctx; rl_set_mouse_pos(x, y); }
static inline void chasm_mouse_cursor(ChasmCtx *ctx, int64_t cursor)      { (void)ctx; rl_mouse_cursor(cursor); }

/* ---- Clipboard ------------------------------------------------------------- */
static inline const char *chasm_get_clipboard(ChasmCtx *ctx)              { (void)ctx; return rl_get_clipboard(); }
static inline void        chasm_set_clipboard(ChasmCtx *ctx, const char *text) { (void)ctx; rl_set_clipboard(text); }

/* ---- Collision ------------------------------------------------------------- */
static inline bool chasm_collide_rects(ChasmCtx *ctx, double x1, double y1, double w1, double h1,
                                        double x2, double y2, double w2, double h2)
    { (void)ctx; return rl_check_collision_recs(x1, y1, w1, h1, x2, y2, w2, h2); }
static inline bool chasm_collide_circles(ChasmCtx *ctx, double x1, double y1, double r1,
                                          double x2, double y2, double r2)
    { (void)ctx; return rl_check_collision_circles(x1, y1, r1, x2, y2, r2); }
static inline bool chasm_point_in_rect(ChasmCtx *ctx, double px, double py,
                                        double rx, double ry, double rw, double rh)
    { (void)ctx; return rl_check_collision_point_rec(px, py, rx, ry, rw, rh); }
