/* Generated by Chasm bootstrap compiler - do not edit. */
#include "chasm_rt.h"

/* Module attributes */
static int64_t g_score;

void chasm_module_init(ChasmCtx *ctx) {
  g_score = 0;
}

void chasm_main(ChasmCtx *ctx) {
  int64_t label = 0;
  100;
  0;
  "great";
  0;
  "ok";
  0;
  chasm_print(ctx, label);
}

