/* Generated by Chasm bootstrap compiler - do not edit. */
#include "chasm_rt.h"

/* Forward declarations */
int64_t chasm_screen_w(ChasmCtx *ctx);
int64_t chasm_screen_h(ChasmCtx *ctx);
void chasm_set_fps(ChasmCtx *ctx, int64_t);
void chasm_set_title(ChasmCtx *ctx, const char*);
int64_t chasm_fps(ChasmCtx *ctx);
double chasm_dt(ChasmCtx *ctx);
double chasm_time(ChasmCtx *ctx);
void chasm_clear(ChasmCtx *ctx, int64_t);
void chasm_draw_rect(ChasmCtx *ctx, double, double, double, double, int64_t);
void chasm_draw_rect_lines(ChasmCtx *ctx, double, double, double, double, int64_t);
void chasm_draw_rect_rounded(ChasmCtx *ctx, double, double, double, double, double, int64_t, int64_t);
void chasm_draw_circle(ChasmCtx *ctx, double, double, double, int64_t);
void chasm_draw_circle_lines(ChasmCtx *ctx, double, double, double, int64_t);
void chasm_draw_line(ChasmCtx *ctx, double, double, double, double, int64_t);
void chasm_draw_line_ex(ChasmCtx *ctx, double, double, double, double, double, int64_t);
void chasm_draw_text(ChasmCtx *ctx, const char*, double, double, int64_t, int64_t);
double chasm_measure_text(ChasmCtx *ctx, const char*, int64_t);
void chasm_draw_fps(ChasmCtx *ctx, double, double);
int64_t chasm_load_texture(ChasmCtx *ctx, const char*);
void chasm_unload_texture(ChasmCtx *ctx, int64_t);
void chasm_draw_texture(ChasmCtx *ctx, int64_t, double, double, int64_t);
void chasm_draw_texture_ex(ChasmCtx *ctx, int64_t, double, double, double, double, int64_t);
void chasm_draw_texture_rect(ChasmCtx *ctx, int64_t, double, double, double, double, double, double, int64_t);
int64_t chasm_texture_w(ChasmCtx *ctx, int64_t);
int64_t chasm_texture_h(ChasmCtx *ctx, int64_t);
int64_t chasm_load_font(ChasmCtx *ctx, const char*);
void chasm_draw_text_ex(ChasmCtx *ctx, int64_t, const char*, double, double, double, double, int64_t);
void chasm_init_audio(ChasmCtx *ctx);
void chasm_close_audio(ChasmCtx *ctx);
int64_t chasm_load_sound(ChasmCtx *ctx, const char*);
void chasm_play_sound(ChasmCtx *ctx, int64_t);
void chasm_stop_sound(ChasmCtx *ctx, int64_t);
int64_t chasm_load_music(ChasmCtx *ctx, const char*);
void chasm_play_music(ChasmCtx *ctx, int64_t);
void chasm_update_music(ChasmCtx *ctx, int64_t);
void chasm_stop_music(ChasmCtx *ctx, int64_t);
bool chasm_key_down(ChasmCtx *ctx, int64_t);
bool chasm_key_pressed(ChasmCtx *ctx, int64_t);
bool chasm_key_released(ChasmCtx *ctx, int64_t);
bool chasm_key_up(ChasmCtx *ctx, int64_t);
int64_t chasm_key_last(ChasmCtx *ctx);
double chasm_mouse_x(ChasmCtx *ctx);
double chasm_mouse_y(ChasmCtx *ctx);
double chasm_mouse_dx(ChasmCtx *ctx);
double chasm_mouse_dy(ChasmCtx *ctx);
bool chasm_mouse_down(ChasmCtx *ctx, int64_t);
bool chasm_mouse_pressed(ChasmCtx *ctx, int64_t);
bool chasm_mouse_released(ChasmCtx *ctx, int64_t);
double chasm_mouse_wheel(ChasmCtx *ctx);
void chasm_hide_cursor(ChasmCtx *ctx);
void chasm_show_cursor(ChasmCtx *ctx);
bool chasm_collide_rects(ChasmCtx *ctx, double, double, double, double, double, double, double, double);
bool chasm_collide_circles(ChasmCtx *ctx, double, double, double, double, double, double);
bool chasm_point_in_rect(ChasmCtx *ctx, double, double, double, double, double, double);
int64_t chasm_ball_color(ChasmCtx *ctx, const char*);
int64_t chasm_trail_color(ChasmCtx *ctx, const char*);
double chasm_ball_speed(ChasmCtx *ctx, const char*);
const char* chasm_state_label(ChasmCtx *ctx, const char*);
void chasm_on_tick(ChasmCtx *ctx, double);
void chasm_on_draw(ChasmCtx *ctx);

/* Module attributes */
static double g_x;
static double g_y;
static double g_vx;
static double g_vy;
static double g_radius;
static const char* g_state;

void chasm_module_init(ChasmCtx *ctx) {
  g_x = 400.0;
  g_y = 300.0;
  g_vx = 200.0;
  g_vy = 150.0;
  g_radius = 24.0;
  g_state = "normal";
}

int64_t chasm_ball_color(ChasmCtx *ctx, const char* state) {
  return ((strcmp(state, "normal") == 0) ? 0x4488ffff : ((strcmp(state, "slow") == 0) ? 0x44ff88ff : 0xffaa22ff));
}

int64_t chasm_trail_color(ChasmCtx *ctx, const char* state) {
  return ((strcmp(state, "normal") == 0) ? 0x4488ff33 : ((strcmp(state, "slow") == 0) ? 0x44ff8833 : 0xffaa2233));
}

double chasm_ball_speed(ChasmCtx *ctx, const char* state) {
  return ((strcmp(state, "normal") == 0) ? 1.0 : ((strcmp(state, "slow") == 0) ? 0.3 : 5.5));
}

const char* chasm_state_label(ChasmCtx *ctx, const char* state) {
  return ((strcmp(state, "normal") == 0) ? "NORMAL" : ((strcmp(state, "slow") == 0) ? "SLOW" : "BOOST"));
}

void chasm_on_tick(ChasmCtx *ctx, double dt) {
  g_state = "normal";
  if (chasm_key_down(ctx, 340)) {
    g_state = "slow";
  }
  if (chasm_key_down(ctx, 32)) {
    g_state = "boost";
  }
  double effective_dt = (dt * chasm_ball_speed(ctx, g_state));
  g_x = (g_x + (g_vx * effective_dt));
  g_y = (g_y + (g_vy * effective_dt));
  if (g_x < g_radius) {
    g_x = g_radius;
    g_vx = chasm_abs(ctx, g_vx);
  }
  if (g_x > (800.0 - g_radius)) {
    g_x = (800.0 - g_radius);
    g_vx = (0.0 - chasm_abs(ctx, g_vx));
  }
  if (g_y < g_radius) {
    g_y = g_radius;
    g_vy = chasm_abs(ctx, g_vy);
  }
  if (g_y > (600.0 - g_radius)) {
    g_y = (600.0 - g_radius);
    g_vy = (0.0 - chasm_abs(ctx, g_vy));
  }
}

void chasm_on_draw(ChasmCtx *ctx) {
  chasm_clear(ctx, 0x181820ff);
  chasm_draw_circle_lines(ctx, g_x, g_y, (g_radius + 6.0), chasm_trail_color(ctx, g_state));
  chasm_draw_circle(ctx, g_x, g_y, g_radius, chasm_ball_color(ctx, g_state));
  chasm_draw_text(ctx, "Chasm + Raylib 5.5", 12.0, 12.0, 20, 0xffffffff);
  chasm_draw_text(ctx, "SHIFT: slow  |  SPACE: boost", 12.0, 38.0, 16, 0x888888ff);
  chasm_draw_text(ctx, chasm_state_label(ctx, g_state), 12.0, 60.0, 16, chasm_ball_color(ctx, g_state));
  chasm_draw_fps(ctx, 12.0, 580.0);
}

