/* Generated by Chasm bootstrap compiler - do not edit. */
#include "chasm_rt.h"

/* Forward declarations */
int64_t chasm_screen_w(ChasmCtx *ctx);
int64_t chasm_screen_h(ChasmCtx *ctx);
void chasm_set_fps(ChasmCtx *ctx, int64_t);
void chasm_set_title(ChasmCtx *ctx, const char*);
int64_t chasm_fps(ChasmCtx *ctx);
double chasm_dt(ChasmCtx *ctx);
double chasm_time(ChasmCtx *ctx);
void chasm_clear(ChasmCtx *ctx, int64_t);
void chasm_draw_rect(ChasmCtx *ctx, double, double, double, double, int64_t);
void chasm_draw_rect_lines(ChasmCtx *ctx, double, double, double, double, int64_t);
void chasm_draw_rect_rounded(ChasmCtx *ctx, double, double, double, double, double, int64_t, int64_t);
void chasm_draw_circle(ChasmCtx *ctx, double, double, double, int64_t);
void chasm_draw_circle_lines(ChasmCtx *ctx, double, double, double, int64_t);
void chasm_draw_line(ChasmCtx *ctx, double, double, double, double, int64_t);
void chasm_draw_line_ex(ChasmCtx *ctx, double, double, double, double, double, int64_t);
void chasm_draw_text(ChasmCtx *ctx, const char*, double, double, int64_t, int64_t);
double chasm_measure_text(ChasmCtx *ctx, const char*, int64_t);
void chasm_draw_fps(ChasmCtx *ctx, double, double);
int64_t chasm_load_texture(ChasmCtx *ctx, const char*);
void chasm_unload_texture(ChasmCtx *ctx, int64_t);
void chasm_draw_texture(ChasmCtx *ctx, int64_t, double, double, int64_t);
void chasm_draw_texture_ex(ChasmCtx *ctx, int64_t, double, double, double, double, int64_t);
void chasm_draw_texture_rect(ChasmCtx *ctx, int64_t, double, double, double, double, double, double, int64_t);
int64_t chasm_texture_w(ChasmCtx *ctx, int64_t);
int64_t chasm_texture_h(ChasmCtx *ctx, int64_t);
int64_t chasm_load_font(ChasmCtx *ctx, const char*);
void chasm_draw_text_ex(ChasmCtx *ctx, int64_t, const char*, double, double, double, double, int64_t);
void chasm_init_audio(ChasmCtx *ctx);
void chasm_close_audio(ChasmCtx *ctx);
int64_t chasm_load_sound(ChasmCtx *ctx, const char*);
void chasm_play_sound(ChasmCtx *ctx, int64_t);
void chasm_stop_sound(ChasmCtx *ctx, int64_t);
int64_t chasm_load_music(ChasmCtx *ctx, const char*);
void chasm_play_music(ChasmCtx *ctx, int64_t);
void chasm_update_music(ChasmCtx *ctx, int64_t);
void chasm_stop_music(ChasmCtx *ctx, int64_t);
bool chasm_key_down(ChasmCtx *ctx, int64_t);
bool chasm_key_pressed(ChasmCtx *ctx, int64_t);
bool chasm_key_released(ChasmCtx *ctx, int64_t);
bool chasm_key_up(ChasmCtx *ctx, int64_t);
int64_t chasm_key_last(ChasmCtx *ctx);
double chasm_mouse_x(ChasmCtx *ctx);
double chasm_mouse_y(ChasmCtx *ctx);
double chasm_mouse_dx(ChasmCtx *ctx);
double chasm_mouse_dy(ChasmCtx *ctx);
bool chasm_mouse_down(ChasmCtx *ctx, int64_t);
bool chasm_mouse_pressed(ChasmCtx *ctx, int64_t);
bool chasm_mouse_released(ChasmCtx *ctx, int64_t);
double chasm_mouse_wheel(ChasmCtx *ctx);
void chasm_hide_cursor(ChasmCtx *ctx);
void chasm_show_cursor(ChasmCtx *ctx);
bool chasm_sound_playing(ChasmCtx *ctx, int64_t);
void chasm_sound_volume(ChasmCtx *ctx, int64_t, double);
void chasm_sound_pitch(ChasmCtx *ctx, int64_t, double);
void chasm_pause_sound(ChasmCtx *ctx, int64_t);
void chasm_resume_sound(ChasmCtx *ctx, int64_t);
bool chasm_music_playing(ChasmCtx *ctx, int64_t);
void chasm_music_volume(ChasmCtx *ctx, int64_t, double);
void chasm_music_pitch(ChasmCtx *ctx, int64_t, double);
double chasm_music_length(ChasmCtx *ctx, int64_t);
double chasm_music_played(ChasmCtx *ctx, int64_t);
void chasm_pause_music(ChasmCtx *ctx, int64_t);
void chasm_resume_music(ChasmCtx *ctx, int64_t);
bool chasm_window_resized(ChasmCtx *ctx);
void chasm_set_window_size(ChasmCtx *ctx, int64_t, int64_t);
void chasm_toggle_fullscreen(ChasmCtx *ctx);
bool chasm_is_fullscreen(ChasmCtx *ctx);
bool chasm_window_focused(ChasmCtx *ctx);
void chasm_draw_triangle(ChasmCtx *ctx, double, double, double, double, double, double, int64_t);
void chasm_draw_triangle_lines(ChasmCtx *ctx, double, double, double, double, double, double, int64_t);
void chasm_draw_ellipse(ChasmCtx *ctx, double, double, double, double, int64_t);
void chasm_draw_ring(ChasmCtx *ctx, double, double, double, double, double, double, int64_t, int64_t);
void chasm_draw_poly(ChasmCtx *ctx, double, double, int64_t, double, double, int64_t);
void chasm_draw_texture_tiled(ChasmCtx *ctx, int64_t, double, double, double, double, double, double, double, double, int64_t);
void chasm_set_texture_filter(ChasmCtx *ctx, int64_t, int64_t);
void chasm_camera2d_begin(ChasmCtx *ctx, double, double, double, double, double, double);
void chasm_camera2d_end(ChasmCtx *ctx);
double chasm_world_to_screen_x(ChasmCtx *ctx, double, double, double, double, double, double, double, double);
double chasm_world_to_screen_y(ChasmCtx *ctx, double, double, double, double, double, double, double, double);
bool chasm_gamepad_available(ChasmCtx *ctx, int64_t);
bool chasm_gamepad_button_down(ChasmCtx *ctx, int64_t, int64_t);
bool chasm_gamepad_button_pressed(ChasmCtx *ctx, int64_t, int64_t);
double chasm_gamepad_axis(ChasmCtx *ctx, int64_t, int64_t);
void chasm_set_mouse_pos(ChasmCtx *ctx, double, double);
void chasm_mouse_cursor(ChasmCtx *ctx, int64_t);
const char* chasm_get_clipboard(ChasmCtx *ctx);
void chasm_set_clipboard(ChasmCtx *ctx, const char*);
bool chasm_collide_rects(ChasmCtx *ctx, double, double, double, double, double, double, double, double);
bool chasm_collide_circles(ChasmCtx *ctx, double, double, double, double, double, double);
bool chasm_point_in_rect(ChasmCtx *ctx, double, double, double, double, double, double);
void chasm_on_init(ChasmCtx *ctx);
double chasm_dir_x(ChasmCtx *ctx, double);
double chasm_dir_y(ChasmCtx *ctx, double);
double chasm_distance(ChasmCtx *ctx, double, double, double, double);
int64_t chasm_enemies_remaining(ChasmCtx *ctx);
void chasm_spawn_bullet(ChasmCtx *ctx, double);
void chasm_move_bullets(ChasmCtx *ctx, double);
void chasm_move_enemies(ChasmCtx *ctx, double);
void chasm_check_bullet_enemy_hits(ChasmCtx *ctx);
void chasm_check_player_enemy_hits(ChasmCtx *ctx);
void chasm_reset_game(ChasmCtx *ctx);
void chasm_on_tick(ChasmCtx *ctx, double);
void chasm_draw_player(ChasmCtx *ctx, double, double, double, bool);
void chasm_draw_enemy(ChasmCtx *ctx, double, double, double);
void chasm_draw_arena(ChasmCtx *ctx);
void chasm_on_draw(ChasmCtx *ctx);

/* Arena-backed array helpers for @attr arrays */
/* array_fixed_in: allocates data from arena at fixed capacity — never grows. */
static inline ChasmArray chasm_array_fixed_in(ChasmArena *arena, int64_t cap) {
    if (cap <= 0) cap = 8;
    void *d = chasm_alloc(arena, (size_t)cap * 8, 8);
    if (!d) return (ChasmArray){NULL, 0, 0};
    return (ChasmArray){d, 0, cap};
}
/* push_fixed: bounds-checked push — aborts on overflow (no realloc). */
static inline void chasm_array_push_fixed(ChasmCtx *ctx, ChasmArray *a, int64_t v) {
    (void)ctx;
    if (a->len >= a->cap) { fprintf(stderr, "chasm: array_fixed overflow (cap=%lld)\n", (long long)a->cap); abort(); }
    ((int64_t*)a->data)[a->len++] = v;
}
/* array_new_in: arena-backed growable array (bump-copy on growth). */
static inline ChasmArray chasm_array_new_in(ChasmArena *arena, int64_t cap) {
    if (cap <= 0) cap = 8;
    void *d = chasm_alloc(arena, (size_t)cap * 8, 8);
    if (!d) return (ChasmArray){NULL, 0, 0};
    return (ChasmArray){d, 0, cap};
}
static inline void chasm_array_push_in(ChasmArena *arena, ChasmArray *a, int64_t v) {
    if (a->len >= a->cap) {
        int64_t new_cap = a->cap * 2 + 8;
        void *nd = chasm_alloc(arena, (size_t)new_cap * 8, 8);
        if (nd && a->data) memcpy(nd, a->data, (size_t)a->len * 8);
        a->data = nd; a->cap = new_cap;
    }
    if (a->data) ((int64_t*)a->data)[a->len++] = v;
}

/* Module attributes */
static double g_world_width;
static double g_world_height;
static double g_player_x;
static double g_player_y;
static double g_player_angle;
static double g_player_speed;
static double g_camera_x;
static double g_camera_y;
static ChasmArray g_bullet_x;
static ChasmArray g_bullet_y;
static ChasmArray g_bullet_vel_x;
static ChasmArray g_bullet_vel_y;
static ChasmArray g_bullet_active;
static ChasmArray g_enemy_x;
static ChasmArray g_enemy_y;
static ChasmArray g_enemy_alive;
static int64_t g_score;
static int64_t g_high_score;
static double g_shoot_cooldown;
static int64_t g_game_over;
static int64_t g_win;
static double g_time_alive;

void chasm_module_init(ChasmCtx *ctx) {
  g_world_width = 800.0;
  g_world_height = 600.0;
  g_player_x = 400.0;
  g_player_y = 300.0;
  g_player_angle = 0.0;
  g_player_speed = 180.0;
  g_camera_x = 400.0;
  g_camera_y = 300.0;
  g_bullet_x = chasm_array_fixed_in(&ctx->script, 4);
  g_bullet_y = chasm_array_fixed_in(&ctx->script, 4);
  g_bullet_vel_x = chasm_array_fixed_in(&ctx->script, 4);
  g_bullet_vel_y = chasm_array_fixed_in(&ctx->script, 4);
  g_bullet_active = chasm_array_fixed_in(&ctx->script, 4);
  g_enemy_x = chasm_array_fixed_in(&ctx->script, 8);
  g_enemy_y = chasm_array_fixed_in(&ctx->script, 8);
  g_enemy_alive = chasm_array_fixed_in(&ctx->script, 8);
  g_score = 0;
  g_high_score = 0;
  g_shoot_cooldown = 0.0;
  g_game_over = 0;
  g_win = 0;
  g_time_alive = 0.0;
}

void chasm_on_init(ChasmCtx *ctx) {
  int64_t slot = 0;
  while (slot < 4) {
    chasm_array_push_fixed(ctx, &g_bullet_x, 0);
    chasm_array_push_fixed(ctx, &g_bullet_y, 0);
    chasm_array_push_fixed(ctx, &g_bullet_vel_x, 0);
    chasm_array_push_fixed(ctx, &g_bullet_vel_y, 0);
    chasm_array_push_fixed(ctx, &g_bullet_active, 0);
    slot = (slot + 1);
  }
  chasm_array_push_fixed(ctx, &g_enemy_x, 100);
  chasm_array_push_fixed(ctx, &g_enemy_y, 100);
  chasm_array_push_fixed(ctx, &g_enemy_x, 700);
  chasm_array_push_fixed(ctx, &g_enemy_y, 100);
  chasm_array_push_fixed(ctx, &g_enemy_x, 100);
  chasm_array_push_fixed(ctx, &g_enemy_y, 500);
  chasm_array_push_fixed(ctx, &g_enemy_x, 700);
  chasm_array_push_fixed(ctx, &g_enemy_y, 500);
  chasm_array_push_fixed(ctx, &g_enemy_x, 400);
  chasm_array_push_fixed(ctx, &g_enemy_y, 80);
  chasm_array_push_fixed(ctx, &g_enemy_x, 400);
  chasm_array_push_fixed(ctx, &g_enemy_y, 520);
  chasm_array_push_fixed(ctx, &g_enemy_x, 80);
  chasm_array_push_fixed(ctx, &g_enemy_y, 300);
  chasm_array_push_fixed(ctx, &g_enemy_x, 720);
  chasm_array_push_fixed(ctx, &g_enemy_y, 300);
  slot = 0;
  while (slot < 8) {
    chasm_array_push_fixed(ctx, &g_enemy_alive, 1);
    slot = (slot + 1);
  }
}

double chasm_dir_x(ChasmCtx *ctx, double angle) {
  return chasm_cos(ctx, chasm_deg_to_rad(ctx, angle));
}

double chasm_dir_y(ChasmCtx *ctx, double angle) {
  return chasm_sin(ctx, chasm_deg_to_rad(ctx, angle));
}

double chasm_distance(ChasmCtx *ctx, double ax, double ay, double bx, double by) {
  double delta_x = (ax - bx);
  double delta_y = (ay - by);
  return chasm_sqrt(ctx, ((delta_x * delta_x) + (delta_y * delta_y)));
}

int64_t chasm_enemies_remaining(ChasmCtx *ctx) {
  int64_t count = 0;
  int64_t i = 0;
  while (i < 8) {
    count = (count + chasm_array_get(ctx, &g_enemy_alive, i));
    i = (i + 1);
  }
  return count;
}

void chasm_spawn_bullet(ChasmCtx *ctx, double angle) {
  double speed = 420.0;
  double dir_x_v = chasm_dir_x(ctx, angle);
  double dir_y_v = chasm_dir_y(ctx, angle);
  int64_t slot = 0;
  while (slot < 4) {
    if (chasm_array_get(ctx, &g_bullet_active, slot) == 0) {
      chasm_array_set(ctx, &g_bullet_x, slot, chasm_to_int(ctx, g_player_x));
      chasm_array_set(ctx, &g_bullet_y, slot, chasm_to_int(ctx, g_player_y));
      chasm_array_set(ctx, &g_bullet_vel_x, slot, chasm_to_int(ctx, (dir_x_v * speed)));
      chasm_array_set(ctx, &g_bullet_vel_y, slot, chasm_to_int(ctx, (dir_y_v * speed)));
      chasm_array_set(ctx, &g_bullet_active, slot, 1);
      return;
    }
    slot = (slot + 1);
  }
}

void chasm_move_bullets(ChasmCtx *ctx, double dt) {
  int64_t slot = 0;
  while (slot < 4) {
    if (chasm_array_get(ctx, &g_bullet_active, slot) == 1) {
      double new_x = (chasm_to_float(ctx, chasm_array_get(ctx, &g_bullet_x, slot)) + (chasm_to_float(ctx, chasm_array_get(ctx, &g_bullet_vel_x, slot)) * dt));
      double new_y = (chasm_to_float(ctx, chasm_array_get(ctx, &g_bullet_y, slot)) + (chasm_to_float(ctx, chasm_array_get(ctx, &g_bullet_vel_y, slot)) * dt));
      chasm_array_set(ctx, &g_bullet_x, slot, chasm_to_int(ctx, new_x));
      chasm_array_set(ctx, &g_bullet_y, slot, chasm_to_int(ctx, new_y));
      if ((((new_x < 0.0) || (new_x > g_world_width)) || (new_y < 0.0)) || (new_y > g_world_height)) {
        chasm_array_set(ctx, &g_bullet_active, slot, 0);
      }
    }
    slot = (slot + 1);
  }
}

void chasm_move_enemies(ChasmCtx *ctx, double dt) {
  int64_t i = 0;
  while (i < 8) {
    if (chasm_array_get(ctx, &g_enemy_alive, i) == 1) {
      double ex = chasm_to_float(ctx, chasm_array_get(ctx, &g_enemy_x, i));
      double ey = chasm_to_float(ctx, chasm_array_get(ctx, &g_enemy_y, i));
      double dx = (g_player_x - ex);
      double dy = (g_player_y - ey);
      double dist = chasm_sqrt(ctx, ((dx * dx) + (dy * dy)));
      if (dist > 1.0) {
        chasm_array_set(ctx, &g_enemy_x, i, chasm_to_int(ctx, (ex + (((dx / dist) * 60.0) * dt))));
        chasm_array_set(ctx, &g_enemy_y, i, chasm_to_int(ctx, (ey + (((dy / dist) * 60.0) * dt))));
      }
    }
    i = (i + 1);
  }
}

void chasm_check_bullet_enemy_hits(ChasmCtx *ctx) {
  int64_t bullet = 0;
  while (bullet < 4) {
    if (chasm_array_get(ctx, &g_bullet_active, bullet) == 1) {
      double bx = chasm_to_float(ctx, chasm_array_get(ctx, &g_bullet_x, bullet));
      double by = chasm_to_float(ctx, chasm_array_get(ctx, &g_bullet_y, bullet));
      int64_t enemy = 0;
      while (enemy < 8) {
        if (chasm_array_get(ctx, &g_enemy_alive, enemy) == 1) {
          double ex = chasm_to_float(ctx, chasm_array_get(ctx, &g_enemy_x, enemy));
          double ey = chasm_to_float(ctx, chasm_array_get(ctx, &g_enemy_y, enemy));
          if (chasm_distance(ctx, bx, by, ex, ey) < 22.0) {
            chasm_array_set(ctx, &g_enemy_alive, enemy, 0);
            chasm_array_set(ctx, &g_bullet_active, bullet, 0);
            g_score = (g_score + 100);
          }
        }
        enemy = (enemy + 1);
      }
    }
    bullet = (bullet + 1);
  }
}

void chasm_check_player_enemy_hits(ChasmCtx *ctx) {
  int64_t i = 0;
  while (i < 8) {
    if (chasm_array_get(ctx, &g_enemy_alive, i) == 1) {
      double ex = chasm_to_float(ctx, chasm_array_get(ctx, &g_enemy_x, i));
      double ey = chasm_to_float(ctx, chasm_array_get(ctx, &g_enemy_y, i));
      if (chasm_distance(ctx, g_player_x, g_player_y, ex, ey) < 20.0) {
        g_game_over = 1;
      }
    }
    i = (i + 1);
  }
}

void chasm_reset_game(ChasmCtx *ctx) {
  g_player_x = 400.0;
  g_player_y = 300.0;
  g_player_angle = 0.0;
  g_score = 0;
  g_game_over = 0;
  g_win = 0;
  g_time_alive = 0.0;
  g_shoot_cooldown = 0.0;
  int64_t slot = 0;
  while (slot < 4) {
    chasm_array_set(ctx, &g_bullet_active, slot, 0);
    slot = (slot + 1);
  }
  chasm_array_set(ctx, &g_enemy_x, 0, 100);
  chasm_array_set(ctx, &g_enemy_y, 0, 100);
  chasm_array_set(ctx, &g_enemy_x, 1, 700);
  chasm_array_set(ctx, &g_enemy_y, 1, 100);
  chasm_array_set(ctx, &g_enemy_x, 2, 100);
  chasm_array_set(ctx, &g_enemy_y, 2, 500);
  chasm_array_set(ctx, &g_enemy_x, 3, 700);
  chasm_array_set(ctx, &g_enemy_y, 3, 500);
  chasm_array_set(ctx, &g_enemy_x, 4, 400);
  chasm_array_set(ctx, &g_enemy_y, 4, 80);
  chasm_array_set(ctx, &g_enemy_x, 5, 400);
  chasm_array_set(ctx, &g_enemy_y, 5, 520);
  chasm_array_set(ctx, &g_enemy_x, 6, 80);
  chasm_array_set(ctx, &g_enemy_y, 6, 300);
  chasm_array_set(ctx, &g_enemy_x, 7, 720);
  chasm_array_set(ctx, &g_enemy_y, 7, 300);
  int64_t i = 0;
  while (i < 8) {
    chasm_array_set(ctx, &g_enemy_alive, i, 1);
    i = (i + 1);
  }
}

void chasm_on_tick(ChasmCtx *ctx, double dt) {
  if ((g_game_over == 1) || (g_win == 1)) {
    if (chasm_key_pressed(ctx, 257)) {
      chasm_reset_game(ctx);
    }
    return;
  }
  g_time_alive = (g_time_alive + dt);
  double input_x = 0.0;
  double input_y = 0.0;
  if (chasm_key_down(ctx, 65) || chasm_key_down(ctx, 263)) {
    input_x = (input_x - 1.0);
  }
  if (chasm_key_down(ctx, 68) || chasm_key_down(ctx, 262)) {
    input_x = (input_x + 1.0);
  }
  if (chasm_key_down(ctx, 87) || chasm_key_down(ctx, 265)) {
    input_y = (input_y - 1.0);
  }
  if (chasm_key_down(ctx, 83) || chasm_key_down(ctx, 264)) {
    input_y = (input_y + 1.0);
  }
  if (chasm_gamepad_available(ctx, 0)) {
    double axis_x = chasm_gamepad_axis(ctx, 0, 0);
    double axis_y = chasm_gamepad_axis(ctx, 0, 1);
    if ((axis_x > 0.15) || (axis_x < (0.0 - 0.15))) {
      input_x = (input_x + axis_x);
    }
    if ((axis_y > 0.15) || (axis_y < (0.0 - 0.15))) {
      input_y = (input_y + axis_y);
    }
  }
  if ((input_x != 0.0) && (input_y != 0.0)) {
    input_x = (input_x * 0.7071);
    input_y = (input_y * 0.7071);
  }
  g_player_x = chasm_copy_to_script(ctx, chasm_clamp(ctx, (g_player_x + ((input_x * g_player_speed) * dt)), 16.0, (g_world_width - 16.0)));
  g_player_y = chasm_copy_to_script(ctx, chasm_clamp(ctx, (g_player_y + ((input_y * g_player_speed) * dt)), 16.0, (g_world_height - 16.0)));
  if ((input_x != 0.0) || (input_y != 0.0)) {
    g_player_angle = chasm_copy_to_script(ctx, chasm_rad_to_deg(ctx, chasm_atan2(ctx, input_y, input_x)));
  }
  g_shoot_cooldown = (g_shoot_cooldown - dt);
  int64_t wants_to_shoot = 0;
  if (chasm_key_pressed(ctx, 32)) {
    wants_to_shoot = 1;
  }
  if (chasm_gamepad_available(ctx, 0)) {
    if (chasm_gamepad_button_pressed(ctx, 0, 0)) {
      wants_to_shoot = 1;
    }
  }
  if ((wants_to_shoot == 1) && (g_shoot_cooldown <= 0.0)) {
    chasm_spawn_bullet(ctx, g_player_angle);
    g_shoot_cooldown = 0.25;
  }
  chasm_move_bullets(ctx, dt);
  chasm_move_enemies(ctx, dt);
  chasm_check_bullet_enemy_hits(ctx);
  chasm_check_player_enemy_hits(ctx);
  if (chasm_enemies_remaining(ctx) == 0) {
    g_win = 1;
    if (g_score > g_high_score) {
      g_high_score = chasm_persist_copy(ctx, g_score);
    }
  }
  g_camera_x = (g_camera_x + (((g_player_x - g_camera_x) * 5.0) * dt));
  g_camera_y = (g_camera_y + (((g_player_y - g_camera_y) * 5.0) * dt));
}

void chasm_draw_player(ChasmCtx *ctx, double x, double y, double angle, bool focused) {
  int64_t color = 0x44aaFFFF;
  if (!(focused)) {
    color = 0x446688FF;
  }
  chasm_draw_poly(ctx, x, y, 5, 14.0, angle, color);
  double forward_x = chasm_dir_x(ctx, angle);
  double forward_y = chasm_dir_y(ctx, angle);
  double nose_x = (x + (forward_x * 18.0));
  double nose_y = (y + (forward_y * 18.0));
  double left_x = (x + (chasm_dir_x(ctx, (angle + 120.0)) * 10.0));
  double left_y = (y + (chasm_dir_y(ctx, (angle + 120.0)) * 10.0));
  double right_x = (x + (chasm_dir_x(ctx, (angle - 120.0)) * 10.0));
  double right_y = (y + (chasm_dir_y(ctx, (angle - 120.0)) * 10.0));
  chasm_draw_triangle(ctx, nose_x, nose_y, left_x, left_y, right_x, right_y, 0xFFFFFFFF);
  chasm_draw_ring(ctx, x, y, 15.0, 18.0, 0.0, 360.0, 16, 0x2244FFAA);
}

void chasm_draw_enemy(ChasmCtx *ctx, double x, double y, double time) {
  double pulse = (chasm_sin(ctx, (time * 3.0)) * 3.0);
  chasm_draw_ring(ctx, x, y, (10.0 + pulse), (18.0 + pulse), 0.0, 360.0, 12, 0xFF4422CC);
  chasm_draw_ellipse(ctx, x, y, 10.0, 8.0, 0xFF6644FF);
  chasm_draw_triangle_lines(ctx, x, (y - 16.0), (x - 14.0), (y + 10.0), (x + 14.0), (y + 10.0), 0xFF2200FF);
}

void chasm_draw_arena(ChasmCtx *ctx) {
  chasm_draw_rect_lines(ctx, 0.0, 0.0, g_world_width, g_world_height, 0x334455FF);
  chasm_draw_line(ctx, 0.0, 150.0, g_world_width, 150.0, 0x1a2233FF);
  chasm_draw_line(ctx, 0.0, 300.0, g_world_width, 300.0, 0x1a2233FF);
  chasm_draw_line(ctx, 0.0, 450.0, g_world_width, 450.0, 0x1a2233FF);
  chasm_draw_line(ctx, 200.0, 0.0, 200.0, g_world_height, 0x1a2233FF);
  chasm_draw_line(ctx, 400.0, 0.0, 400.0, g_world_height, 0x1a2233FF);
  chasm_draw_line(ctx, 600.0, 0.0, 600.0, g_world_height, 0x1a2233FF);
}

void chasm_on_draw(ChasmCtx *ctx) {
  chasm_clear(ctx, 0x0d1117FF);
  bool focused = chasm_window_focused(ctx);
  if (g_game_over == 1) {
    chasm_draw_text(ctx, "GAME OVER", 260.0, 240.0, 48, 0xFF4422FF);
    chasm_draw_text(ctx, "Press ENTER to restart", 240.0, 310.0, 20, 0x888888FF);
    chasm_draw_text(ctx, chasm_str_concat(ctx, "Score: ", chasm_int_to_str(ctx, g_score)), 330.0, 350.0, 20, 0xFFFFFFFF);
    return;
  }
  if (g_win == 1) {
    chasm_draw_text(ctx, "YOU WIN!", 290.0, 240.0, 48, 0x44FF88FF);
    chasm_draw_text(ctx, "Press ENTER to restart", 240.0, 310.0, 20, 0x888888FF);
    chasm_draw_text(ctx, chasm_str_concat(ctx, "Score: ", chasm_int_to_str(ctx, g_score)), 330.0, 350.0, 20, 0xFFFFFFFF);
    return;
  }
  chasm_camera2d_begin(ctx, g_camera_x, g_camera_y, g_player_x, g_player_y, 0.0, 1.0);
  chasm_draw_arena(ctx);
  int64_t i = 0;
  while (i < 8) {
    if (chasm_array_get(ctx, &g_enemy_alive, i) == 1) {
      chasm_draw_enemy(ctx, chasm_to_float(ctx, chasm_array_get(ctx, &g_enemy_x, i)), chasm_to_float(ctx, chasm_array_get(ctx, &g_enemy_y, i)), g_time_alive);
    }
    i = (i + 1);
  }
  int64_t slot = 0;
  while (slot < 4) {
    if (chasm_array_get(ctx, &g_bullet_active, slot) == 1) {
      double bx = chasm_to_float(ctx, chasm_array_get(ctx, &g_bullet_x, slot));
      double by = chasm_to_float(ctx, chasm_array_get(ctx, &g_bullet_y, slot));
      chasm_draw_ellipse(ctx, bx, by, 5.0, 3.0, 0xFFFF44FF);
      chasm_draw_circle(ctx, bx, by, 3.0, 0xFFFFAAFF);
    }
    slot = (slot + 1);
  }
  chasm_draw_player(ctx, g_player_x, g_player_y, g_player_angle, focused);
  chasm_camera2d_end(ctx);
  chasm_draw_text(ctx, "SHAPE SHOOTER", 12.0, 12.0, 22, 0x44AAFFFF);
  chasm_draw_text(ctx, chasm_str_concat(ctx, "Score: ", chasm_int_to_str(ctx, g_score)), 12.0, 40.0, 18, 0xFFFFFFFF);
  chasm_draw_text(ctx, chasm_str_concat(ctx, "Best:  ", chasm_int_to_str(ctx, g_high_score)), 12.0, 62.0, 16, 0xFFAA44FF);
  chasm_draw_text(ctx, chasm_str_concat(ctx, "Enemies: ", chasm_int_to_str(ctx, chasm_enemies_remaining(ctx))), 12.0, 84.0, 16, 0xFF6644FF);
  chasm_draw_text(ctx, "WASD/Arrows: move  SPACE: shoot", 12.0, 576.0, 14, 0x556677FF);
  chasm_draw_fps(ctx, 720.0, 12.0);
  if (!(focused)) {
    chasm_draw_text(ctx, "[ paused - click to focus ]", 240.0, 290.0, 18, 0x888888AA);
  }
}

