/* engine/main.c — Chasm + Raylib standalone host loop.
 *
 * Build manually:
 *   cc -o game script.c main.c \
 *     -I../raylib-5.5_macos/include -I. \
 *     -L../raylib-5.5_macos/lib -lraylib \
 *     -framework OpenGL -framework Cocoa -framework IOKit \
 *     -framework CoreVideo -framework CoreAudio -framework AudioToolbox
 *
 * Or use: chasm run --engine raylib game.chasm
 *
 * The compiled Chasm script MUST define:
 *   on_tick(dt: float) -> void   — game logic, input, physics
 *   on_draw()          -> void   — all rendering (called between Begin/EndDrawing)
 *
 * Optional hooks (stub provided if missing):
 *   on_init()   -> void          — called once after window opens (load assets)
 *   on_unload() -> void          — called before window closes (save state)
 */
#include "chasm_rl.h"

/* Generated by Chasm compiler */
void chasm_module_init(ChasmCtx *ctx);
void chasm_on_tick(ChasmCtx *ctx, double dt);
void chasm_on_draw(ChasmCtx *ctx);

/* Optional — defined as no-ops if the script doesn't provide them */
__attribute__((weak)) void chasm_on_init(ChasmCtx *ctx)   { (void)ctx; }
__attribute__((weak)) void chasm_on_unload(ChasmCtx *ctx) { (void)ctx; }

int main(void) {
    /* ---- Arena layout ------------------------------------------ *
     *  frame      (1 MB)  — cleared every tick at end of frame      *
     *  script     (4 MB)  — cleared on hot-reload; holds live state  *
     *  persistent (16 MB) — never cleared; save data, loaded assets  *
     * ------------------------------------------------------------ */
    static uint8_t frame_mem  [ 1 * 1024 * 1024];
    static uint8_t script_mem [ 4 * 1024 * 1024];
    static uint8_t persist_mem[16 * 1024 * 1024];

    ChasmCtx ctx = {
        .frame      = { frame_mem,   0, sizeof(frame_mem)   },
        .script     = { script_mem,  0, sizeof(script_mem)  },
        .persistent = { persist_mem, 0, sizeof(persist_mem) },
    };

    /* Run @attr initializers (script-level constructors) */
    chasm_module_init(&ctx);

    /* Open window */
    InitWindow(800, 600, "Chasm Game");
    SetTargetFPS(60);

    /* Optional: load assets, start music, etc. */
    chasm_on_init(&ctx);

    /* ---- Main loop --------------------------------------------- */
    while (!WindowShouldClose()) {
        double dt = (double)GetFrameTime();

        /* Tick: input + game logic (runs before drawing) */
        chasm_on_tick(&ctx, dt);

        /* Draw: everything between Begin/EndDrawing */
        BeginDrawing();
        ClearBackground(BLACK);
        chasm_on_draw(&ctx);
        EndDrawing();

        /* Reclaim all frame-lifetime allocations */
        chasm_clear_frame(&ctx);
    }

    /* Optional: flush saves, unload assets */
    chasm_on_unload(&ctx);
    CloseWindow();
    return 0;
}
