/// C code emitter.
///
/// Takes a fully-lowered `IrModule` and emits a single C99 translation unit.
/// A companion `emitRuntimeHeader` produces `chasm_rt.h`, which the emitted
/// source `#include`s.
///
/// Lifetime threading:
///   Every generated function receives a `ChasmCtx *ctx` as its first
///   parameter.  Frame allocations use `ctx->frame`, script `ctx->script`,
///   persistent `ctx->persistent`.  Primitive values (int, float, bool, atom,
///   string) use C value semantics; `promote` on a scalar is a plain copy.
///   Future: structs will call `chasm_arena_copy` for arena-to-arena moves.
///
/// Naming conventions:
///   - Chasm functions  → `chasm_<name>`
///   - Module @attrs    → `g_<name>`
///   - IR temporaries   → `t<id>` (e.g., `t0`, `t1`)
///   - Labels           → `L<id>` (e.g., `L0`, `L1`)

const std    = @import("std");
const ir     = @import("ir");
const reload = @import("reload");

const IrModule   = ir.IrModule;
const IrFunction = ir.IrFunction;
const IrAttr     = ir.IrAttr;
const IrParam    = ir.IrParam;
const Instr      = ir.Instr;
const Temp       = ir.Temp;
const TempId     = ir.TempId;
const LabelId    = ir.LabelId;
const BinaryOp   = ir.BinaryOp;
const UnaryOp    = ir.UnaryOp;
const Lifetime   = @import("runtime").Lifetime;

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/// Emit a complete C99 translation unit for `module`.
/// Set `is_imported` to true when emitting a dependency module: skips
/// `chasm_module_init` and `chasm_reload_migrate` to avoid duplicate symbols.
pub fn emitModule(module: IrModule, writer: anytype) !void {
    try emitModuleOpts(module, false, "chasm_rt.h", writer);
}

pub fn emitModuleRaylib(module: IrModule, writer: anytype) !void {
    try emitModuleOpts(module, false, "chasm_rl.h", writer);
}

pub fn emitModuleImported(module: IrModule, writer: anytype) !void {
    try emitModuleOpts(module, true, "chasm_rt.h", writer);
}

fn emitModuleOpts(module: IrModule, is_imported: bool, runtime_header: []const u8, writer: anytype) !void {
    try writer.print(
        \\/* Generated by Chasm compiler — do not edit. */
        \\
        , .{});
    try writer.print("#include \"{s}\"\n\n", .{runtime_header});

    // ---- Enum variant #defines ---------------------------------------------
    if (module.enum_variants.len > 0) {
        try writer.print("/* Enum variants */\n", .{});
        for (module.enum_variants) |ev| {
            try writer.print("#define CHASM_ENUM_{s}_{s} {d}\n",
                .{ ev.enum_name, ev.variant_name, ev.index });
        }
        try writer.print("\n", .{});
    }

    // ---- Extern function comments ------------------------------------------
    if (module.extern_fns.len > 0) {
        try writer.print("/* Extern functions */\n", .{});
        for (module.extern_fns) |ef| {
            try writer.print("// extern: {s}\n", .{ef.c_name});
        }
        try writer.print("\n", .{});
    }

    // ---- Global attribute storage ------------------------------------------
    if (module.attrs.len > 0) {
        try writer.print("/* Module attributes */\n", .{});
        for (module.attrs) |a| {
            try writer.print("static {s} g_{s};\n",
                .{ cTypeOf(a.type_id), a.name });
        }
        try writer.print("\n", .{});
    }

    // ---- Attribute initialiser function (skipped for imported modules) ------
    if (!is_imported) {
        try writer.print("/* Attribute initialiser — call once at module load */\n", .{});
        try writer.print("void chasm_module_init(ChasmCtx *ctx) {{\n", .{});
        if (module.attr_init_instrs.len > 0) {
            try emitTempDeclsForSlice(module.attr_init_temps, writer);
            for (module.attr_init_instrs) |instr|
                try emitInstr(instr, module.attr_init_temps, module.extern_fns, writer, 1);
            // Write computed init values into global storage.
            for (module.attrs) |attr| {
                try writer.print("    g_{s} = t{d};\n", .{ attr.name, attr.init_temp });
            }
        } else {
            try writer.print("    (void)ctx;\n", .{});
        }
        try writer.print("}}\n\n", .{});
    }

    // ---- Forward declarations ----------------------------------------------
    if (module.functions.len > 0) {
        try writer.print("/* Forward declarations */\n", .{});
        for (module.functions) |f| try emitForwardDecl(f, writer);
        try writer.print("\n", .{});
    }

    // ---- Imported module forward declarations ------------------------------
    if (module.imported_fwd_decls.len > 0) {
        try writer.print("/* Imported module forward declarations */\n", .{});
        for (module.imported_fwd_decls) |fwd| {
            try writer.print("{s} chasm_{s}(ChasmCtx *ctx", .{ fwd.ret_c_type, fwd.name });
            for (fwd.param_c_types) |pt| {
                try writer.print(", {s}", .{pt});
            }
            try writer.print(");\n", .{});
        }
        try writer.print("\n", .{});
    }

    // ---- Function definitions ----------------------------------------------
    for (module.functions) |f| try emitFunction(f, module.extern_fns, writer);

    // ---- Hot-reload migration stub (skipped for imported modules) ----------
    if (is_imported) return;
    // Build a pseudo-report treating all attrs as preserved (first compile).
    var alloc_buf: [4096]u8 = undefined;
    var fba = std.heap.FixedBufferAllocator.init(&alloc_buf);
    var pseudo_diffs = std.ArrayListUnmanaged(reload.AttrDiff){};
    for (module.attrs) |a| {
        pseudo_diffs.append(fba.allocator(), .{
            .name         = a.name,
            .compat       = .preserved,
            .old_type_id  = a.type_id,
            .new_type_id  = a.type_id,
            .old_lifetime = a.lifetime,
            .new_lifetime = a.lifetime,
        }) catch break;
    }
    const stub_report = reload.ReloadReport{
        .diffs       = pseudo_diffs.items,
        .safe_reload = true,
        .preserved   = @intCast(pseudo_diffs.items.len),
        .lost = 0, .added = 0, .removed = 0,
    };
    try reload.emitMigrationFn(stub_report, writer);
}

/// Emit the `chasm_rt.h` runtime header.
pub fn emitRuntimeHeader(writer: anytype) !void {
    try writer.print(
        \\#pragma once
        \\/* Chasm runtime — minimal arena allocator C header */
        \\#include <stdint.h>
        \\#include <stdbool.h>
        \\#include <stddef.h>
        \\#include <string.h>
        \\
        \\typedef struct {{
        \\    uint8_t *base;
        \\    size_t   used;
        \\    size_t   cap;
        \\}} ChasmArena;
        \\
        \\typedef struct {{
        \\    ChasmArena frame;
        \\    ChasmArena script;
        \\    ChasmArena persistent;
        \\}} ChasmCtx;
        \\
        \\static inline void *chasm_alloc(ChasmArena *a, size_t n, size_t align) {{
        \\    size_t adj = (align - (a->used & (align - 1))) & (align - 1);
        \\    if (a->used + adj + n > a->cap) return NULL;
        \\    a->used += adj;
        \\    void *p = a->base + a->used;
        \\    a->used += n;
        \\    return p;
        \\}}
        \\
        \\static inline void chasm_clear_frame(ChasmCtx *ctx) {{
        \\    ctx->frame.used = 0;
        \\}}
        \\
        \\/* Promote a scalar value to a longer-lived arena (primitive: no-op copy). */
        \\#define chasm_promote_scalar(val) (val)
        \\
        \\/* ------------------------------------------------------------------ */
        \\/* Chasm standard library                                             */
        \\/* ------------------------------------------------------------------ */
        \\#include <math.h>
        \\#include <stdio.h>
        \\#include <stdlib.h>
        \\#include <string.h>
        \\#include <time.h>
        \\
        \\/* ---- math -------------------------------------------------------- */
        \\static inline double chasm_scale(ChasmCtx *ctx, double v, double f)          {{ (void)ctx; return v * f; }}
        \\static inline double chasm_clamp(ChasmCtx *ctx, double v, double lo, double hi) {{ (void)ctx; return v < lo ? lo : v > hi ? hi : v; }}
        \\static inline double chasm_abs(ChasmCtx *ctx, double v)                      {{ (void)ctx; return fabs(v); }}
        \\static inline double chasm_sqrt(ChasmCtx *ctx, double v)                     {{ (void)ctx; return sqrt(v); }}
        \\static inline double chasm_pow(ChasmCtx *ctx, double b, double e)            {{ (void)ctx; return pow(b, e); }}
        \\static inline double chasm_floor(ChasmCtx *ctx, double v)                    {{ (void)ctx; return floor(v); }}
        \\static inline double chasm_ceil(ChasmCtx *ctx, double v)                     {{ (void)ctx; return ceil(v); }}
        \\static inline double chasm_round(ChasmCtx *ctx, double v)                    {{ (void)ctx; return round(v); }}
        \\static inline double chasm_lerp(ChasmCtx *ctx, double a, double b, double t) {{ (void)ctx; return a + (b - a) * t; }}
        \\static inline double chasm_sign(ChasmCtx *ctx, double v)                     {{ (void)ctx; return v > 0 ? 1.0 : v < 0 ? -1.0 : 0.0; }}
        \\static inline double chasm_sin(ChasmCtx *ctx, double v)                      {{ (void)ctx; return sin(v); }}
        \\static inline double chasm_cos(ChasmCtx *ctx, double v)                      {{ (void)ctx; return cos(v); }}
        \\static inline double chasm_tan(ChasmCtx *ctx, double v)                      {{ (void)ctx; return tan(v); }}
        \\static inline double chasm_atan2(ChasmCtx *ctx, double y, double x)          {{ (void)ctx; return atan2(y, x); }}
        \\static inline double chasm_min(ChasmCtx *ctx, double a, double b)            {{ (void)ctx; return a < b ? a : b; }}
        \\static inline double chasm_max(ChasmCtx *ctx, double a, double b)            {{ (void)ctx; return a > b ? a : b; }}
        \\static inline double chasm_deg_to_rad(ChasmCtx *ctx, double d)               {{ (void)ctx; return d * (3.14159265358979323846 / 180.0); }}
        \\static inline double chasm_rad_to_deg(ChasmCtx *ctx, double r)               {{ (void)ctx; return r * (180.0 / 3.14159265358979323846); }}
        \\static inline double chasm_fract(ChasmCtx *ctx, double v)                    {{ (void)ctx; return v - floor(v); }}
        \\static inline double chasm_wrap(ChasmCtx *ctx, double v, double lo, double hi) {{
        \\    (void)ctx; double r = hi - lo; if (r == 0) return lo;
        \\    return v - r * floor((v - lo) / r);
        \\}}
        \\static inline double chasm_snap(ChasmCtx *ctx, double v, double step)        {{ (void)ctx; return step == 0 ? v : floor(v / step + 0.5) * step; }}
        \\static inline double chasm_smooth_step(ChasmCtx *ctx, double e0, double e1, double x) {{
        \\    (void)ctx; double t = (x-e0)/(e1-e0); t = t<0?0:t>1?1:t;
        \\    return t*t*(3-2*t);
        \\}}
        \\static inline double chasm_smoother_step(ChasmCtx *ctx, double e0, double e1, double x) {{
        \\    (void)ctx; double t = (x-e0)/(e1-e0); t = t<0?0:t>1?1:t;
        \\    return t*t*t*(t*(t*6-15)+10);
        \\}}
        \\static inline double chasm_ping_pong(ChasmCtx *ctx, double t, double len) {{
        \\    (void)ctx; if (len == 0) return 0;
        \\    double v = fmod(t, 2*len); if (v < 0) v += 2*len;
        \\    return v <= len ? v : 2*len - v;
        \\}}
        \\static inline double chasm_move_toward(ChasmCtx *ctx, double cur, double target, double delta) {{
        \\    (void)ctx; double d = target - cur;
        \\    return fabs(d) <= delta ? target : cur + (d > 0 ? delta : -delta);
        \\}}
        \\static inline double chasm_angle_diff(ChasmCtx *ctx, double a, double b) {{
        \\    (void)ctx; double d = fmod(b - a + 3.14159265358979323846, 6.28318530717958647692) - 3.14159265358979323846;
        \\    return d < -3.14159265358979323846 ? d + 6.28318530717958647692 : d;
        \\}}
        \\
        \\/* ---- easing ------------------------------------------------------ */
        \\static inline double chasm_ease_in(ChasmCtx *ctx, double t)          {{ (void)ctx; t=t<0?0:t>1?1:t; return t*t; }}
        \\static inline double chasm_ease_out(ChasmCtx *ctx, double t)         {{ (void)ctx; t=t<0?0:t>1?1:t; return 1-(1-t)*(1-t); }}
        \\static inline double chasm_ease_in_out(ChasmCtx *ctx, double t)      {{ (void)ctx; t=t<0?0:t>1?1:t; return t<0.5?2*t*t:1-2*(1-t)*(1-t); }}
        \\static inline double chasm_ease_in_cubic(ChasmCtx *ctx, double t)    {{ (void)ctx; t=t<0?0:t>1?1:t; return t*t*t; }}
        \\static inline double chasm_ease_out_cubic(ChasmCtx *ctx, double t)   {{ (void)ctx; t=t<0?0:t>1?1:t; return 1-(1-t)*(1-t)*(1-t); }}
        \\static inline double chasm_ease_in_out_cubic(ChasmCtx *ctx, double t) {{
        \\    (void)ctx; t=t<0?0:t>1?1:t;
        \\    return t<0.5 ? 4*t*t*t : 1-4*(1-t)*(1-t)*(1-t);
        \\}}
        \\static inline double chasm_ease_in_elastic(ChasmCtx *ctx, double t) {{
        \\    (void)ctx; if(t<=0)return 0; if(t>=1)return 1;
        \\    return -pow(2,10*t-10)*sin((t*10-10.75)*6.28318530717958647692/3.0);
        \\}}
        \\static inline double chasm_ease_out_bounce(ChasmCtx *ctx, double t) {{
        \\    (void)ctx; if(t<1/2.75) return 7.5625*t*t;
        \\    if(t<2/2.75){{t-=1.5/2.75;return 7.5625*t*t+0.75;}}
        \\    if(t<2.5/2.75){{t-=2.25/2.75;return 7.5625*t*t+0.9375;}}
        \\    t-=2.625/2.75; return 7.5625*t*t+0.984375;
        \\}}
        \\
        \\/* ---- vec2 (flat: pass x,y as separate floats) -------------------- */
        \\static inline double chasm_vec2_len(ChasmCtx *ctx, double x, double y)                   {{ (void)ctx; return sqrt(x*x+y*y); }}
        \\static inline double chasm_vec2_dot(ChasmCtx *ctx, double ax, double ay, double bx, double by) {{ (void)ctx; return ax*bx+ay*by; }}
        \\static inline double chasm_vec2_dist(ChasmCtx *ctx, double ax, double ay, double bx, double by) {{ return chasm_vec2_len(ctx, bx-ax, by-ay); }}
        \\static inline double chasm_vec2_angle(ChasmCtx *ctx, double x, double y)                 {{ (void)ctx; return atan2(y, x); }}
        \\static inline double chasm_vec2_cross(ChasmCtx *ctx, double ax, double ay, double bx, double by) {{ (void)ctx; return ax*by - ay*bx; }}
        \\static inline double chasm_vec2_norm_x(ChasmCtx *ctx, double x, double y) {{
        \\    (void)ctx; double l = sqrt(x*x+y*y); return l==0?0:x/l;
        \\}}
        \\static inline double chasm_vec2_norm_y(ChasmCtx *ctx, double x, double y) {{
        \\    (void)ctx; double l = sqrt(x*x+y*y); return l==0?0:y/l;
        \\}}
        \\
        \\/* ---- bitwise ----------------------------------------------------- */
        \\static inline int64_t chasm_bit_and(ChasmCtx *ctx, int64_t a, int64_t b) {{ (void)ctx; return a & b; }}
        \\static inline int64_t chasm_bit_or (ChasmCtx *ctx, int64_t a, int64_t b) {{ (void)ctx; return a | b; }}
        \\static inline int64_t chasm_bit_xor(ChasmCtx *ctx, int64_t a, int64_t b) {{ (void)ctx; return a ^ b; }}
        \\static inline int64_t chasm_bit_not(ChasmCtx *ctx, int64_t a)            {{ (void)ctx; return ~a; }}
        \\static inline int64_t chasm_bit_shl(ChasmCtx *ctx, int64_t a, int64_t n) {{ (void)ctx; return a << (n & 63); }}
        \\static inline int64_t chasm_bit_shr(ChasmCtx *ctx, int64_t a, int64_t n) {{ (void)ctx; return a >> (n & 63); }}
        \\
        \\/* ---- random ------------------------------------------------------ */
        \\/* Seed once on first call via a static flag. */
        \\static inline double chasm_rand(ChasmCtx *ctx) {{
        \\    static int seeded = 0; (void)ctx;
        \\    if (!seeded) {{ srand((unsigned)time(NULL)); seeded = 1; }}
        \\    return (double)rand() / ((double)RAND_MAX + 1.0);
        \\}}
        \\static inline double chasm_rand_range(ChasmCtx *ctx, double lo, double hi) {{
        \\    return lo + chasm_rand(ctx) * (hi - lo);
        \\}}
        \\static inline int64_t chasm_rand_int(ChasmCtx *ctx, int64_t lo, int64_t hi) {{
        \\    if (hi <= lo) return lo;
        \\    return lo + (int64_t)(chasm_rand(ctx) * (double)(hi - lo));
        \\}}
        \\
        \\/* ---- string ------------------------------------------------------ */
        \\static inline int64_t     chasm_str_len(ChasmCtx *ctx, const char *s) {{ (void)ctx; return s ? (int64_t)strlen(s) : 0; }}
        \\static inline const char *chasm_str_concat(ChasmCtx *ctx, const char *a, const char *b) {{
        \\    if (!a) a=""; if (!b) b="";
        \\    size_t la=strlen(a), lb=strlen(b);
        \\    char *o=(char*)chasm_alloc(&ctx->frame,la+lb+1,1); if(!o)return "";
        \\    memcpy(o,a,la); memcpy(o+la,b,lb); o[la+lb]='\0'; return o;
        \\}}
        \\static inline const char *chasm_str_repeat(ChasmCtx *ctx, const char *s, int64_t n) {{
        \\    if (!s||n<=0) return "";
        \\    size_t l=strlen(s); char *o=(char*)chasm_alloc(&ctx->frame,l*(size_t)n+1,1); if(!o)return "";
        \\    for(int64_t i=0;i<n;i++) memcpy(o+i*l,s,l); o[l*n]='\0'; return o;
        \\}}
        \\static inline const char *chasm_str_slice(ChasmCtx *ctx, const char *s, int64_t start, int64_t end) {{
        \\    if (!s) return "";
        \\    int64_t l=(int64_t)strlen(s);
        \\    if(start<0)start=0; if(end>l)end=l; if(start>=end)return "";
        \\    size_t n=(size_t)(end-start);
        \\    char *o=(char*)chasm_alloc(&ctx->frame,n+1,1); if(!o)return "";
        \\    memcpy(o,s+start,n); o[n]='\0'; return o;
        \\}}
        \\static inline int64_t     chasm_str_char_at(ChasmCtx *ctx, const char *s, int64_t i) {{ (void)ctx; if(!s)return 0; int64_t l=(int64_t)strlen(s); if(i<0||i>=l)return 0; return (uint8_t)s[i]; }}
        \\static inline const char *chasm_str_from_char(ChasmCtx *ctx, int64_t c) {{
        \\    char *o=(char*)chasm_alloc(&ctx->frame,2,1); if(!o)return "";
        \\    o[0]=(char)c; o[1]='\0'; return o;
        \\}}
        \\static inline const char *chasm_str_upper(ChasmCtx *ctx, const char *s) {{
        \\    if (!s) return "";
        \\    size_t l=strlen(s); char *o=(char*)chasm_alloc(&ctx->frame,l+1,1); if(!o)return "";
        \\    for(size_t i=0;i<=l;i++) o[i]=(char)(s[i]>='a'&&s[i]<='z'?s[i]-32:s[i]); return o;
        \\}}
        \\static inline const char *chasm_str_lower(ChasmCtx *ctx, const char *s) {{
        \\    if (!s) return "";
        \\    size_t l=strlen(s); char *o=(char*)chasm_alloc(&ctx->frame,l+1,1); if(!o)return "";
        \\    for(size_t i=0;i<=l;i++) o[i]=(char)(s[i]>='A'&&s[i]<='Z'?s[i]+32:s[i]); return o;
        \\}}
        \\static inline const char *chasm_str_trim(ChasmCtx *ctx, const char *s) {{
        \\    if (!s) return "";
        \\    while(*s==' '||*s=='\t'||*s=='\n'||*s=='\r') s++;
        \\    size_t l=strlen(s);
        \\    while(l>0&&(s[l-1]==' '||s[l-1]=='\t'||s[l-1]=='\n'||s[l-1]=='\r')) l--;
        \\    char *o=(char*)chasm_alloc(&ctx->frame,l+1,1); if(!o)return "";
        \\    memcpy(o,s,l); o[l]='\0'; return o;
        \\}}
        \\static inline bool        chasm_str_contains(ChasmCtx *ctx, const char *s, const char *sub)    {{ (void)ctx; return s&&sub&&strstr(s,sub)!=NULL; }}
        \\static inline bool        chasm_str_starts_with(ChasmCtx *ctx, const char *s, const char *pre) {{ (void)ctx; if(!s||!pre)return 0; return strncmp(s,pre,strlen(pre))==0; }}
        \\static inline bool        chasm_str_ends_with(ChasmCtx *ctx, const char *s, const char *suf)   {{
        \\    (void)ctx; if(!s||!suf)return 0;
        \\    size_t ls=strlen(s),lx=strlen(suf); return ls>=lx&&memcmp(s+ls-lx,suf,lx)==0;
        \\}}
        \\static inline bool        chasm_str_eq(ChasmCtx *ctx, const char *a, const char *b) {{ (void)ctx; return a&&b&&strcmp(a,b)==0; }}
        \\static inline const char *chasm_int_to_str(ChasmCtx *ctx, int64_t v) {{
        \\    char *b=(char*)chasm_alloc(&ctx->frame,24,1); if(!b)return "";
        \\    snprintf(b,24,"%lld",(long long)v); return b;
        \\}}
        \\static inline const char *chasm_float_to_str(ChasmCtx *ctx, double v) {{
        \\    char *b=(char*)chasm_alloc(&ctx->frame,32,1); if(!b)return "";
        \\    snprintf(b,32,"%g",v); return b;
        \\}}
        \\
        \\/* ---- type conversion --------------------------------------------- */
        \\static inline int64_t chasm_to_int(ChasmCtx *ctx, double v)   {{ (void)ctx; return (int64_t)v; }}
        \\static inline double  chasm_to_float(ChasmCtx *ctx, int64_t v){{ (void)ctx; return (double)v; }}
        \\static inline bool    chasm_to_bool(ChasmCtx *ctx, int64_t v) {{ (void)ctx; return v != 0; }}
        \\
        \\/* ---- color (packed 0xRRGGBBAA) ----------------------------------- */
        \\static inline int64_t chasm_rgb(ChasmCtx *ctx, int64_t r, int64_t g, int64_t b)           {{ (void)ctx; return ((r&0xFF)<<24)|((g&0xFF)<<16)|((b&0xFF)<<8)|0xFF; }}
        \\static inline int64_t chasm_rgba(ChasmCtx *ctx, int64_t r, int64_t g, int64_t b, int64_t a){{ (void)ctx; return ((r&0xFF)<<24)|((g&0xFF)<<16)|((b&0xFF)<<8)|(a&0xFF); }}
        \\static inline int64_t chasm_color_r(ChasmCtx *ctx, int64_t c) {{ (void)ctx; return (c>>24)&0xFF; }}
        \\static inline int64_t chasm_color_g(ChasmCtx *ctx, int64_t c) {{ (void)ctx; return (c>>16)&0xFF; }}
        \\static inline int64_t chasm_color_b(ChasmCtx *ctx, int64_t c) {{ (void)ctx; return (c>>8)&0xFF; }}
        \\static inline int64_t chasm_color_a(ChasmCtx *ctx, int64_t c) {{ (void)ctx; return c&0xFF; }}
        \\static inline int64_t chasm_color_lerp(ChasmCtx *ctx, int64_t a, int64_t b, double t) {{
        \\    int64_t ar=(a>>24)&0xFF, ag=(a>>16)&0xFF, ab=(a>>8)&0xFF, aa=a&0xFF;
        \\    int64_t br=(b>>24)&0xFF, bg=(b>>16)&0xFF, bb=(b>>8)&0xFF, ba=b&0xFF;
        \\    int64_t r=(int64_t)(ar+(br-ar)*t), g=(int64_t)(ag+(bg-ag)*t);
        \\    int64_t bl2=(int64_t)(ab+(bb-ab)*t), al=(int64_t)(aa+(ba-aa)*t);
        \\    return ((r&0xFF)<<24)|((g&0xFF)<<16)|((bl2&0xFF)<<8)|(al&0xFF);
        \\}}
        \\static inline int64_t chasm_color_mix(ChasmCtx *ctx, int64_t a, int64_t b, double t) {{ return chasm_color_lerp(ctx,a,b,t); }}
        \\
        \\/* ---- time -------------------------------------------------------- */
        \\static inline double  chasm_time_now(ChasmCtx *ctx) {{ (void)ctx; struct timespec ts; clock_gettime(CLOCK_REALTIME,&ts); return (double)ts.tv_sec+(double)ts.tv_nsec*1e-9; }}
        \\static inline int64_t chasm_time_ms(ChasmCtx *ctx)  {{ (void)ctx; struct timespec ts; clock_gettime(CLOCK_REALTIME,&ts); return (int64_t)ts.tv_sec*1000+ts.tv_nsec/1000000; }}
        \\
        \\/* ---- arrays ------------------------------------------------------ */
        \\typedef struct {{ void *data; int64_t len; int64_t cap; }} ChasmArray;
        \\static inline ChasmArray chasm_array_new(ChasmCtx *ctx, int64_t cap) {{
        \\    void *d = chasm_alloc(&ctx->frame, (size_t)(cap > 0 ? cap : 8) * 8, 8);
        \\    return (ChasmArray){{d, 0, cap > 0 ? cap : 8}};
        \\}}
        \\static inline void    chasm_array_push(ChasmCtx *ctx, ChasmArray *a, int64_t v)          {{ (void)ctx; if(a->len<a->cap) ((int64_t*)a->data)[a->len++]=v; }}
        \\static inline int64_t chasm_array_pop (ChasmCtx *ctx, ChasmArray *a)                     {{ (void)ctx; return a->len>0?((int64_t*)a->data)[--a->len]:0; }}
        \\static inline int64_t chasm_array_get (ChasmCtx *ctx, ChasmArray *a, int64_t i)          {{ (void)ctx; return(i>=0&&i<a->len)?((int64_t*)a->data)[i]:0; }}
        \\static inline void    chasm_array_set (ChasmCtx *ctx, ChasmArray *a, int64_t i, int64_t v){{ (void)ctx; if(i>=0&&i<a->len)((int64_t*)a->data)[i]=v; }}
        \\static inline int64_t chasm_array_len (ChasmCtx *ctx, ChasmArray *a)                     {{ (void)ctx; return a->len; }}
        \\static inline void    chasm_array_clear(ChasmCtx *ctx, ChasmArray *a)                    {{ (void)ctx; a->len=0; }}
        \\
        \\/* ---- i/o --------------------------------------------------------- */
        \\static inline void chasm_print(ChasmCtx *ctx, int64_t v)       {{ (void)ctx; printf("%lld\n", (long long)v); }}
        \\static inline void chasm_print_f(ChasmCtx *ctx, double v)      {{ (void)ctx; printf("%g\n", v); }}
        \\static inline void chasm_print_s(ChasmCtx *ctx, const char *v) {{ (void)ctx; printf("%s\n", v ? v : "(nil)"); }}
        \\static inline void chasm_print_b(ChasmCtx *ctx, bool v)        {{ (void)ctx; printf("%s\n", v ? "true" : "false"); }}
        \\static inline void chasm_log(ChasmCtx *ctx, int64_t v)         {{ (void)ctx; fprintf(stderr, "[log] %lld\n", (long long)v); }}
        \\static inline void chasm_assert(ChasmCtx *ctx, bool cond) {{
        \\    (void)ctx; if (!cond) {{ fprintf(stderr, "chasm: assertion failed\n"); abort(); }}
        \\}}
        \\static inline void chasm_assert_eq(ChasmCtx *ctx, int64_t a, int64_t b) {{
        \\    (void)ctx; if (a != b) {{ fprintf(stderr, "chasm: assert_eq failed: %lld != %lld\n", (long long)a, (long long)b); abort(); }}
        \\}}
        \\static inline void chasm_todo(ChasmCtx *ctx) {{
        \\    (void)ctx; fprintf(stderr, "chasm: todo() reached\n"); abort();
        \\}}
        \\
        , .{});
}

/// Emit the `chasm_rl.h` raylib adapter header.
pub fn emitRaylibHeader(writer: anytype) !void {
    try writer.print(
        \\#pragma once
        \\/* chasm_rl.h — Raylib adapter for Chasm scripts.
        \\   Include this in your host BEFORE the compiled script C file.
        \\   Functions use rl_ prefix and match the extern declarations in raylib.chasm. */
        \\#include "raylib.h"
        \\#include "chasm_rt.h"
        \\#include <stdint.h>
        \\#include <stdbool.h>
        \\
        \\/* Color: Chasm packs as int64_t 0xRRGGBBAA */
        \\#define CHASM_TO_RL_COLOR(c) ((Color){{ \
        \\    (unsigned char)(((int64_t)(c)>>24)&0xFF), \
        \\    (unsigned char)(((int64_t)(c)>>16)&0xFF), \
        \\    (unsigned char)(((int64_t)(c)>>8) &0xFF), \
        \\    (unsigned char)( (int64_t)(c)     &0xFF)  \
        \\}})
        \\
        \\/* Handle table for opaque resource types */
        \\#define CHASM_RL_MAX_HANDLES 1024
        \\typedef enum {{ CHASM_RL_NONE=0, CHASM_RL_TEXTURE, CHASM_RL_FONT, CHASM_RL_SOUND, CHASM_RL_MUSIC }} ChasmRlKind;
        \\typedef struct {{
        \\    ChasmRlKind kind;
        \\    union {{ Texture2D texture; Font font; Sound sound; Music music; }} data;
        \\}} ChasmRlHandle;
        \\static ChasmRlHandle chasm_rl_handles[CHASM_RL_MAX_HANDLES];
        \\static int64_t       chasm_rl_handle_next = 1;
        \\static inline int64_t chasm_rl_alloc(ChasmRlKind k) {{
        \\    if (chasm_rl_handle_next >= CHASM_RL_MAX_HANDLES) return 0;
        \\    int64_t id = chasm_rl_handle_next++;
        \\    chasm_rl_handles[id].kind = k;
        \\    return id;
        \\}}
        \\
        \\/* ---- Window ---------------------------------------------------------------- */
        \\static inline void    rl_init_window(int64_t w, int64_t h, const char *title) {{ InitWindow((int)w,(int)h,title); }}
        \\static inline void    rl_set_target_fps(int64_t fps)   {{ SetTargetFPS((int)fps); }}
        \\static inline bool    rl_window_should_close(void)     {{ return WindowShouldClose(); }}
        \\static inline void    rl_close_window(void)            {{ CloseWindow(); }}
        \\static inline int64_t rl_screen_width(void)            {{ return (int64_t)GetScreenWidth(); }}
        \\static inline int64_t rl_screen_height(void)           {{ return (int64_t)GetScreenHeight(); }}
        \\static inline double  rl_frame_time(void)              {{ return (double)GetFrameTime(); }}
        \\static inline double  rl_time(void)                    {{ return (double)GetTime(); }}
        \\static inline int64_t rl_fps(void)                     {{ return (int64_t)GetFPS(); }}
        \\
        \\/* ---- Drawing --------------------------------------------------------------- */
        \\static inline void rl_begin_drawing(void)              {{ BeginDrawing(); }}
        \\static inline void rl_end_drawing(void)                {{ EndDrawing(); }}
        \\static inline void rl_clear_background(int64_t c)      {{ ClearBackground(CHASM_TO_RL_COLOR(c)); }}
        \\static inline void rl_draw_rectangle(double x, double y, double w, double h, int64_t c)
        \\    {{ DrawRectangle((int)x,(int)y,(int)w,(int)h,CHASM_TO_RL_COLOR(c)); }}
        \\static inline void rl_draw_rectangle_lines(double x, double y, double w, double h, int64_t c)
        \\    {{ DrawRectangleLines((int)x,(int)y,(int)w,(int)h,CHASM_TO_RL_COLOR(c)); }}
        \\static inline void rl_draw_circle(double x, double y, double r, int64_t c)
        \\    {{ DrawCircle((int)x,(int)y,(float)r,CHASM_TO_RL_COLOR(c)); }}
        \\static inline void rl_draw_circle_lines(double x, double y, double r, int64_t c)
        \\    {{ DrawCircleLines((int)x,(int)y,(float)r,CHASM_TO_RL_COLOR(c)); }}
        \\static inline void rl_draw_line(double x1, double y1, double x2, double y2, int64_t c)
        \\    {{ DrawLine((int)x1,(int)y1,(int)x2,(int)y2,CHASM_TO_RL_COLOR(c)); }}
        \\static inline void rl_draw_text(const char *text, double x, double y, int64_t size, int64_t c)
        \\    {{ DrawText(text,(int)x,(int)y,(int)size,CHASM_TO_RL_COLOR(c)); }}
        \\static inline double rl_measure_text(const char *text, int64_t size)
        \\    {{ return (double)MeasureText(text,(int)size); }}
        \\static inline void rl_draw_fps(double x, double y) {{ DrawFPS((int)x,(int)y); }}
        \\
        \\/* ---- Texture --------------------------------------------------------------- */
        \\static inline int64_t rl_load_texture(const char *path) {{
        \\    Texture2D t = LoadTexture(path); if (!t.id) return 0;
        \\    int64_t id = chasm_rl_alloc(CHASM_RL_TEXTURE);
        \\    chasm_rl_handles[id].data.texture = t; return id;
        \\}}
        \\static inline void rl_unload_texture(int64_t h) {{
        \\    if (h<=0||h>=CHASM_RL_MAX_HANDLES) return;
        \\    UnloadTexture(chasm_rl_handles[h].data.texture);
        \\    chasm_rl_handles[h].kind = CHASM_RL_NONE;
        \\}}
        \\static inline void rl_draw_texture(int64_t h, double x, double y, int64_t tint) {{
        \\    if (h<=0||h>=CHASM_RL_MAX_HANDLES) return;
        \\    DrawTexture(chasm_rl_handles[h].data.texture,(int)x,(int)y,CHASM_TO_RL_COLOR(tint));
        \\}}
        \\static inline void rl_draw_texture_ex(int64_t h, double x, double y, double rot, double scale, int64_t tint) {{
        \\    if (h<=0||h>=CHASM_RL_MAX_HANDLES) return;
        \\    DrawTextureEx(chasm_rl_handles[h].data.texture,(Vector2){{(float)x,(float)y}},(float)rot,(float)scale,CHASM_TO_RL_COLOR(tint));
        \\}}
        \\static inline int64_t rl_texture_width(int64_t h)  {{ return (h>0&&h<CHASM_RL_MAX_HANDLES)?chasm_rl_handles[h].data.texture.width:0; }}
        \\static inline int64_t rl_texture_height(int64_t h) {{ return (h>0&&h<CHASM_RL_MAX_HANDLES)?chasm_rl_handles[h].data.texture.height:0; }}
        \\
        \\/* ---- Font ------------------------------------------------------------------ */
        \\static inline int64_t rl_load_font(const char *path) {{
        \\    Font f = LoadFont(path);
        \\    int64_t id = chasm_rl_alloc(CHASM_RL_FONT);
        \\    chasm_rl_handles[id].data.font = f; return id;
        \\}}
        \\static inline void rl_draw_text_ex(int64_t h, const char *text, double x, double y, double size, double spacing, int64_t c) {{
        \\    if (h<=0||h>=CHASM_RL_MAX_HANDLES) return;
        \\    DrawTextEx(chasm_rl_handles[h].data.font,text,(Vector2){{(float)x,(float)y}},(float)size,(float)spacing,CHASM_TO_RL_COLOR(c));
        \\}}
        \\
        \\/* ---- Audio ----------------------------------------------------------------- */
        \\static inline void    rl_init_audio(void)            {{ InitAudioDevice(); }}
        \\static inline void    rl_close_audio(void)           {{ CloseAudioDevice(); }}
        \\static inline int64_t rl_load_sound(const char *p) {{
        \\    Sound s = LoadSound(p);
        \\    int64_t id = chasm_rl_alloc(CHASM_RL_SOUND);
        \\    chasm_rl_handles[id].data.sound = s; return id;
        \\}}
        \\static inline void rl_play_sound(int64_t h) {{ if(h>0&&h<CHASM_RL_MAX_HANDLES) PlaySound(chasm_rl_handles[h].data.sound); }}
        \\static inline void rl_stop_sound(int64_t h) {{ if(h>0&&h<CHASM_RL_MAX_HANDLES) StopSound(chasm_rl_handles[h].data.sound); }}
        \\static inline int64_t rl_load_music(const char *p) {{
        \\    Music m = LoadMusicStream(p);
        \\    int64_t id = chasm_rl_alloc(CHASM_RL_MUSIC);
        \\    chasm_rl_handles[id].data.music = m; return id;
        \\}}
        \\static inline void rl_play_music(int64_t h)   {{ if(h>0&&h<CHASM_RL_MAX_HANDLES) PlayMusicStream(chasm_rl_handles[h].data.music); }}
        \\static inline void rl_update_music(int64_t h) {{ if(h>0&&h<CHASM_RL_MAX_HANDLES) UpdateMusicStream(chasm_rl_handles[h].data.music); }}
        \\static inline void rl_stop_music(int64_t h)   {{ if(h>0&&h<CHASM_RL_MAX_HANDLES) StopMusicStream(chasm_rl_handles[h].data.music); }}
        \\
        \\/* ---- Keyboard -------------------------------------------------------------- */
        \\static inline bool    rl_is_key_pressed(int64_t k)  {{ return IsKeyPressed((int)k); }}
        \\static inline bool    rl_is_key_down(int64_t k)      {{ return IsKeyDown((int)k); }}
        \\static inline bool    rl_is_key_released(int64_t k)  {{ return IsKeyReleased((int)k); }}
        \\static inline bool    rl_is_key_up(int64_t k)         {{ return IsKeyUp((int)k); }}
        \\static inline int64_t rl_get_key_pressed(void)        {{ return (int64_t)GetKeyPressed(); }}
        \\
        \\/* ---- Mouse ----------------------------------------------------------------- */
        \\static inline double rl_mouse_x(void)               {{ return (double)GetMouseX(); }}
        \\static inline double rl_mouse_y(void)               {{ return (double)GetMouseY(); }}
        \\static inline double rl_mouse_delta_x(void)         {{ return (double)GetMouseDelta().x; }}
        \\static inline double rl_mouse_delta_y(void)         {{ return (double)GetMouseDelta().y; }}
        \\static inline bool   rl_is_mouse_pressed(int64_t b) {{ return IsMouseButtonPressed((int)b); }}
        \\static inline bool   rl_is_mouse_down(int64_t b)    {{ return IsMouseButtonDown((int)b); }}
        \\static inline bool   rl_is_mouse_released(int64_t b){{ return IsMouseButtonReleased((int)b); }}
        \\static inline double rl_mouse_wheel(void)           {{ return (double)GetMouseWheelMove(); }}
        \\
        \\/* ---- Collision helpers (AABB, circle) ------------------------------------- */
        \\static inline bool rl_check_collision_recs(double x1,double y1,double w1,double h1,
        \\                                            double x2,double y2,double w2,double h2) {{
        \\    Rectangle a={{(float)x1,(float)y1,(float)w1,(float)h1}};
        \\    Rectangle b={{(float)x2,(float)y2,(float)w2,(float)h2}};
        \\    return CheckCollisionRecs(a,b);
        \\}}
        \\static inline bool rl_check_collision_circles(double x1,double y1,double r1,
        \\                                               double x2,double y2,double r2) {{
        \\    return CheckCollisionCircles((Vector2){{(float)x1,(float)y1}},(float)r1,
        \\                                  (Vector2){{(float)x2,(float)y2}},(float)r2);
        \\}}
        \\
        , .{});
}

// ---------------------------------------------------------------------------
// Function emission
// ---------------------------------------------------------------------------

fn emitForwardDecl(f: IrFunction, writer: anytype) !void {
    const ret = inferReturnType(f);
    try writer.print("{s} chasm_{s}(ChasmCtx *ctx",
        .{ cTypeOf(ret), f.name });
    for (f.params) |p| {
        try writer.print(", {s} t{d}", .{ cTypeOf(p.type_id), p.temp_id });
    }
    try writer.print(");\n", .{});
}

fn emitFunction(f: IrFunction, extern_fns: []const ir.IrExternFn, writer: anytype) !void {
    const ret = inferReturnType(f);

    // Signature
    try writer.print("{s} chasm_{s}(ChasmCtx *ctx",
        .{ cTypeOf(ret), f.name });
    for (f.params) |p| {
        try writer.print(", {s} t{d}", .{ cTypeOf(p.type_id), p.temp_id });
    }
    try writer.print(") {{\n", .{});

    // Declare all non-param temps up front so gotos are valid C99.
    try emitTempDeclsForFn(f, writer);

    // Instructions
    for (f.instrs) |instr| try emitInstr(instr, f.temps, extern_fns, writer, 1);

    try writer.print("}}\n\n", .{});
}

/// Declare every non-param temp at the top of the function body.
fn emitTempDeclsForFn(f: IrFunction, writer: anytype) !void {
    // Collect param temp ids so we can skip them.
    var param_set: [256]bool = [_]bool{false} ** 256;
    for (f.params) |p| {
        if (p.temp_id < param_set.len) param_set[p.temp_id] = true;
    }
    for (f.temps) |t| {
        if (t.id < param_set.len and param_set[t.id]) continue;
        if (t.type_id == 6) continue; // T_VOID — no variable needed
        try writer.print("    {s} t{d};\n", .{ cTypeOf(t.type_id), t.id });
    }
    if (f.temps.len > f.params.len) try writer.print("\n", .{});
}

fn emitTempDeclsForSlice(temps: []const Temp, writer: anytype) !void {
    for (temps) |t| {
        if (t.type_id == 6) continue;
        try writer.print("    {s} t{d};\n", .{ cTypeOf(t.type_id), t.id });
    }
    if (temps.len > 0) try writer.print("\n", .{});
}

// ---------------------------------------------------------------------------
// Instruction emission
// ---------------------------------------------------------------------------

fn isExternFn(name: []const u8, extern_fns: []const ir.IrExternFn) ?[]const u8 {
    for (extern_fns) |ef| {
        if (std.mem.eql(u8, ef.name, name)) return ef.c_name;
    }
    return null;
}

fn emitInstr(instr: Instr, temps: []const Temp, extern_fns: []const ir.IrExternFn, writer: anytype, indent: usize) !void {
    // Emit `indent * 4` spaces.
    const spaces = "                "; // 16 spaces
    const pad = spaces[0 .. @min(indent * 4, spaces.len)];

    switch (instr) {
        // ---- Literals ------------------------------------------------------
        .const_int    => |i| try writer.print("{s}t{d} = {d};\n",     .{ pad, i.dest, i.value }),
        .const_float  => |i| try writer.print("{s}t{d} = {d};\n",     .{ pad, i.dest, i.value }),
        .const_bool   => |i| try writer.print("{s}t{d} = {s};\n",     .{ pad, i.dest, if (i.value) "true" else "false" }),
        .const_string => |i| try writer.print("{s}t{d} = \"{s}\";\n", .{ pad, i.dest, i.value }),
        .const_atom   => |i| try writer.print("{s}t{d} = \"{s}\";\n", .{ pad, i.dest, i.value }),

        // ---- Data movement -------------------------------------------------
        .copy    => |i| try writer.print("{s}t{d} = t{d};\n", .{ pad, i.dest, i.src }),
        .promote => |i| {
            // Scalars: plain copy (arena semantics for structs deferred).
            if (i.from == i.to) {
                try writer.print("{s}t{d} = t{d}; /* same-lt copy */\n", .{ pad, i.dest, i.src });
            } else {
                try writer.print("{s}t{d} = chasm_promote_scalar(t{d}); /* {s} -> {s} */\n",
                    .{ pad, i.dest, i.src, @tagName(i.from), @tagName(i.to) });
            }
        },

        // ---- Operations ----------------------------------------------------
        .call => |i| {
            // Check if this is an extern function call
            if (isExternFn(i.callee, extern_fns)) |c_name| {
                // Extern function: emit c_name(args...) directly, no chasm_ prefix, no ctx
                if (i.dest == ir_mod.invalid_temp) {
                    try writer.print("{s}{s}(", .{ pad, c_name });
                } else {
                    try writer.print("{s}t{d} = {s}(", .{ pad, i.dest, c_name });
                }
                for (i.args, 0..) |a, ai| {
                    if (ai > 0) try writer.print(", ", .{});
                    try writer.print("t{d}", .{a});
                }
                try writer.print(");\n", .{});
            } else {
                // print/log dispatch: pick the right C overload by argument type.
                const callee = blk: {
                    const is_io = std.mem.eql(u8, i.callee, "print") or
                                  std.mem.eql(u8, i.callee, "log");
                    if (is_io and i.args.len == 1) {
                        const arg_id = i.args[0];
                        const arg_ty = if (arg_id < temps.len) temps[arg_id].type_id else 0;
                        const suffix: []const u8 = switch (arg_ty) {
                            2 => "_f",  // T_FLOAT
                            3 => "_b",  // T_BOOL
                            4, 5 => "_s", // T_STRING, T_ATOM
                            else => "",   // T_INT / T_UNKNOWN
                        };
                        break :blk try std.fmt.allocPrint(std.heap.page_allocator,
                            "{s}{s}", .{ i.callee, suffix });
                    }
                    break :blk i.callee;
                };
                // Determine which args need to be passed by pointer (array builtins)
                const array_builtins = [_][]const u8{
                    "array_push", "array_pop", "array_get", "array_set",
                    "array_len", "array_clear",
                };
                var is_array_builtin = false;
                for (array_builtins) |ab| {
                    if (std.mem.eql(u8, callee, ab)) { is_array_builtin = true; break; }
                }
                if (i.dest == ir_mod.invalid_temp) {
                    try writer.print("{s}chasm_{s}(ctx", .{ pad, callee });
                } else {
                    try writer.print("{s}t{d} = chasm_{s}(ctx", .{ pad, i.dest, callee });
                }
                for (i.args, 0..) |a, arg_idx| {
                    // First array arg of array builtins needs '&'
                    if (is_array_builtin and arg_idx == 0) {
                        try writer.print(", &t{d}", .{a});
                    } else {
                        try writer.print(", t{d}", .{a});
                    }
                }
                try writer.print(");\n", .{});
            }
        },
        .binary => |i| try writer.print("{s}t{d} = t{d} {s} t{d};\n",
            .{ pad, i.dest, i.left, cBinaryOp(i.op), i.right }),
        .unary  => |i| try writer.print("{s}t{d} = {s}t{d};\n",
            .{ pad, i.dest, cUnaryOp(i.op), i.operand }),

        // ---- Memory --------------------------------------------------------
        .field_get => |i| try writer.print("{s}t{d} = t{d}.{s};\n",   .{ pad, i.dest, i.object, i.field }),
        .field_set => |i| try writer.print("{s}t{d}.{s} = t{d};\n",   .{ pad, i.object, i.field, i.src }),
        .load_attr  => |i| try writer.print("{s}t{d} = g_{s};\n",     .{ pad, i.dest, i.name }),
        .store_attr => |i| try writer.print("{s}g_{s} = t{d};\n",     .{ pad, i.name, i.src }),

        // ---- Control flow --------------------------------------------------
        .label  => |id| try writer.print("L{d}:;\n", .{id}), // trailing ; avoids empty-label C warning
        .branch => |i| try writer.print("{s}if (t{d}) goto L{d}; else goto L{d};\n",
            .{ pad, i.cond, i.then_lbl, i.else_lbl }),
        .jump   => |id| try writer.print("{s}goto L{d};\n", .{ pad, id }),
        .ret    => |t|  try writer.print("{s}return t{d};\n", .{ pad, t }),
        .ret_void =>    try writer.print("{s}return;\n", .{pad}),
    }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

fn inferReturnType(f: IrFunction) u32 {
    for (f.instrs) |instr| {
        switch (instr) {
            .ret => |t| {
                if (t < f.temps.len) return f.temps[t].type_id;
                return 1; // T_INT fallback
            },
            else => {},
        }
    }
    return 6; // T_VOID
}

/// C type string for a TypeId.
fn cTypeOf(type_id: u32) []const u8 {
    return switch (type_id) {
        0 => "int64_t",      // T_UNKNOWN — default to int
        1 => "int64_t",      // T_INT
        2 => "double",       // T_FLOAT
        3 => "bool",         // T_BOOL
        4 => "const char*",  // T_STRING
        5 => "const char*",  // T_ATOM
        6 => "void",         // T_VOID
        7 => "ChasmArray",   // T_ARRAY
        else => "int64_t",   // user-defined: placeholder
    };
}

fn cBinaryOp(op: BinaryOp) []const u8 {
    return switch (op) {
        .add   => "+",
        .sub   => "-",
        .mul   => "*",
        .div   => "/",
        .mod   => "%",
        .eq    => "==",
        .neq   => "!=",
        .lt    => "<",
        .lte   => "<=",
        .gt    => ">",
        .gte   => ">=",
        .@"and" => "&&",
        .@"or"  => "||",
    };
}

fn cUnaryOp(op: UnaryOp) []const u8 {
    return switch (op) {
        .neg => "-",
        .not => "!",
    };
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

const testing  = std.testing;
const ast_mod  = @import("ast");
const sema_mod = @import("sema");
const ir_mod   = @import("ir");
const lower_mod = @import("lower");
const Lexer    = @import("lexer").Lexer;
const Parser   = @import("parser").Parser;
const DiagList = @import("diag").DiagList;
const AstPool  = ast_mod.AstPool;
const Sema     = sema_mod.Sema;
const Lowerer  = lower_mod.Lowerer;

const TestCodegen = struct {
    arena:  std.heap.ArenaAllocator,
    out:    []const u8,

    fn init(src: []const u8) !TestCodegen {
        var arena = std.heap.ArenaAllocator.init(testing.allocator);
        const alloc = arena.allocator();

        var lex    = Lexer.init(src);
        const toks = try lex.tokenize(alloc);
        var pool   = AstPool.init(alloc);
        var diags  = DiagList.init(alloc);
        var parser = Parser.init(toks, &pool, &diags, alloc);
        const top  = try parser.parseFile();

        var sem = Sema.init(&pool, &diags, alloc);
        try sem.analyze(top);
        if (diags.hasErrors()) return error.SemaFailed;

        var lower = Lowerer.init(&pool, &sem, alloc);
        const module = try lower.lower(top);

        var buf: std.ArrayListUnmanaged(u8) = .{};
        try emitModule(module, buf.writer(alloc));

        return .{ .arena = arena, .out = try buf.toOwnedSlice(alloc) };
    }

    fn output(self: *const TestCodegen) []const u8 { return self.out; }

    fn has(self: *const TestCodegen, needle: []const u8) bool {
        return std.mem.indexOf(u8, self.out, needle) != null;
    }

    fn deinit(self: *TestCodegen) void { self.arena.deinit(); }
};

test "emitRuntimeHeader produces valid content" {
    var buf: std.ArrayListUnmanaged(u8) = .{};
    defer buf.deinit(testing.allocator);
    try emitRuntimeHeader(buf.writer(testing.allocator));
    const out = buf.items;
    try testing.expect(std.mem.indexOf(u8, out, "ChasmCtx") != null);
    try testing.expect(std.mem.indexOf(u8, out, "chasm_alloc") != null);
    try testing.expect(std.mem.indexOf(u8, out, "chasm_clear_frame") != null);
}

test "simple function emits correct C" {
    var tc = try TestCodegen.init(
        \\def f() do
        \\  42
        \\end
    );
    defer tc.deinit();
    try testing.expect(tc.has("#include \"chasm_rt.h\""));
    try testing.expect(tc.has("chasm_f(ChasmCtx *ctx)"));
}

test "integer arithmetic" {
    var tc = try TestCodegen.init(
        \\def add(a :: int, b :: int) do
        \\  a + b
        \\end
    );
    defer tc.deinit();
    try testing.expect(tc.has("chasm_add(ChasmCtx *ctx"));
    try testing.expect(tc.has("+"));
}

test "copy_to_script emits promote comment" {
    var tc = try TestCodegen.init(
        \\def f() do
        \\  raw :: frame = 1
        \\  saved :: script = copy_to_script(raw)
        \\end
    );
    defer tc.deinit();
    try testing.expect(tc.has("frame -> script"));
}

test "persist_copy emits promote comment" {
    var tc = try TestCodegen.init(
        \\@score :: script = 0
        \\def on_save() do
        \\  final :: persistent = persist_copy(@score)
        \\end
    );
    defer tc.deinit();
    try testing.expect(tc.has("script -> persistent"));
}

test "@attr store emits global assignment" {
    var tc = try TestCodegen.init(
        \\@score :: script = 0
        \\def tick() do
        \\  v :: script = copy_to_script(1)
        \\  @score = v
        \\end
    );
    defer tc.deinit();
    try testing.expect(tc.has("g_score"));
    try testing.expect(tc.has("g_score ="));
}

test "if/else emits goto structure" {
    var tc = try TestCodegen.init(
        \\def f(x :: int) do
        \\  if x > 0 do
        \\    1
        \\  else
        \\    0
        \\  end
        \\end
    );
    defer tc.deinit();
    try testing.expect(tc.has("if ("));
    try testing.expect(tc.has("goto L"));
    try testing.expect(tc.has("L0:;"));
}

test "while loop emits jump-back structure" {
    var tc = try TestCodegen.init(
        \\def f() do
        \\  i :: frame = 0
        \\  while i < 10 do
        \\    i = i + 1
        \\  end
        \\end
    );
    defer tc.deinit();
    try testing.expect(tc.has("goto L"));   // back-edge jump
    try testing.expect(tc.has("if ("));     // condition branch
}

test "forward declarations emitted before definitions" {
    var tc = try TestCodegen.init(
        \\defp helper() :: int do
        \\  1
        \\end
        \\def caller() do
        \\  helper()
        \\end
    );
    defer tc.deinit();
    const out = tc.output();
    // Forward decl must appear before function body.
    const fwd  = std.mem.indexOf(u8, out, "Forward declarations") orelse return error.Missing;
    const defn = std.mem.indexOf(u8, out, "chasm_helper(ChasmCtx") orelse return error.Missing;
    try testing.expect(fwd < defn);
}

test "full hello.chasm-style module emits C" {
    var tc = try TestCodegen.init(
        \\@score :: script = 0
        \\@high_score :: persistent = 0
        \\defp compute_delta(dt :: f32) :: f32 do
        \\  speed :: frame = 9.8
        \\  speed * dt
        \\end
        \\def on_tick(dt :: f32) do
        \\  delta :: frame = compute_delta(dt)
        \\  saved :: script = copy_to_script(delta)
        \\  @score = saved
        \\end
        \\def on_save() do
        \\  final :: persistent = persist_copy(@score)
        \\  @high_score = final
        \\end
    );
    defer tc.deinit();
    try testing.expect(tc.has("g_score"));
    try testing.expect(tc.has("g_high_score"));
    try testing.expect(tc.has("chasm_compute_delta"));
    try testing.expect(tc.has("chasm_on_tick"));
    try testing.expect(tc.has("chasm_on_save"));
    try testing.expect(tc.has("frame -> script"));
    try testing.expect(tc.has("script -> persistent"));
}
