/* Generated by Chasm bootstrap compiler - do not edit. */
#include "chasm_rt.h"

/* Forward declarations */
void chasm_main(ChasmCtx *ctx);

void chasm_main(ChasmCtx *ctx) {
  chasm_print_s(ctx, "Hello from Chasm!");
  chasm_print(ctx, (1 + 19));
}

