/* Generated by Chasm bootstrap compiler - do not edit. */
#include "chasm_rt.h"

/* Forward declarations */
void chasm_on_tick(ChasmCtx *ctx, double);

/* Module attributes */
static int64_t g_score;
static int64_t g_high_score;

void chasm_module_init(ChasmCtx *ctx) {
  g_score = 0;
  g_high_score = 0;
}

void chasm_on_tick(ChasmCtx *ctx, double dt) {
  g_score = chasm_copy_to_script(ctx, 42);
  g_high_score = chasm_persist_copy(ctx, 42);
}

