/* Generated by Chasm compiler — do not edit. */
#include "chasm_rt.h"

/* Module attributes */
static int64_t g_score;
static int64_t g_high_score;

/* Attribute initialiser — call once at module load */
void chasm_module_init(ChasmCtx *ctx) {
    int64_t t0;
    int64_t t1;

    t0 = 0;
    t1 = 0;
}

/* Forward declarations */
void chasm_compute_delta(ChasmCtx *ctx, int64_t t0);
void chasm_on_tick(ChasmCtx *ctx, int64_t t0);
void chasm_on_save(ChasmCtx *ctx);
void chasm_describe_status(ChasmCtx *ctx, int64_t t0);
void chasm_run_loop(ChasmCtx *ctx, int64_t t0);

void chasm_compute_delta(ChasmCtx *ctx, int64_t t0) {
    double t1;
    double t2;

    t1 = 9.8;
    t2 = t1 * t0;
    return;
}

void chasm_on_tick(ChasmCtx *ctx, int64_t t0) {
    int64_t t1;
    int64_t t2;
    double t3;
    int64_t t4;
    double t5;
    double t6;
    int64_t t7;
    double t8;
    bool t9;
    int64_t t10;
    double t11;
    double t12;

    t1 = chasm_compute_delta(ctx, t0);
    t2 = chasm_promote_scalar(t1); /* frame -> script */
    g_score = t2;
    t3 = 2;
    t4 = chasm_scale(ctx, t1, t3);
    t5 = 0;
    t6 = 100;
    t7 = chasm_clamp(ctx, t4, t5, t6);
    t8 = 50;
    t9 = t7 > t8;
    if (t9) goto L0; else goto L1;
L0:;
    t10 = chasm_promote_scalar(t7); /* frame -> script */
    g_score = t10;
    goto L2;
L1:;
    t11 = 0;
    t12 = chasm_promote_scalar(t11); /* frame -> script */
    g_score = t12;
    goto L2;
L2:;
    return;
}

void chasm_on_save(ChasmCtx *ctx) {
    int64_t t0;
    int64_t t1;

    t0 = g_score;
    t1 = chasm_promote_scalar(t0); /* script -> persistent */
    g_high_score = t1;
    return;
}

void chasm_describe_status(ChasmCtx *ctx, int64_t t0) {
    int64_t t1;
    const char* t2;
    bool t3;
    const char* t4;
    const char* t5;
    bool t6;
    const char* t7;
    const char* t8;
    bool t9;
    const char* t10;
    bool t11;
    const char* t12;

    t2 = "idle";
    t3 = t0 == t2;
    if (t3) goto L1; else goto L2;
L1:;
    t4 = "standing by";
    t1 = t4;
    goto L0;
L2:;
    t5 = "running";
    t6 = t0 == t5;
    if (t6) goto L3; else goto L4;
L3:;
    t7 = "in motion";
    t1 = t7;
    goto L0;
L4:;
    t8 = "dead";
    t9 = t0 == t8;
    if (t9) goto L5; else goto L6;
L5:;
    t10 = "game over";
    t1 = t10;
    goto L0;
L6:;
    t11 = true;
    if (t11) goto L7; else goto L8;
L7:;
    t12 = "unknown";
    t1 = t12;
    goto L0;
L8:;
L0:;
    return;
}

void chasm_run_loop(ChasmCtx *ctx, int64_t t0) {
    int64_t t1;
    bool t2;
    int64_t t3;
    int64_t t4;

    t1 = 0;
    goto L0;
L0:;
    t2 = t1 < t0;
    if (t2) goto L1; else goto L2;
L1:;
    t3 = 1;
    t4 = t1 + t3;
    goto L0;
L2:;
    return;
}

/* Hot-reload migration — call this after dlopen'ing the new module.
 * The host engine must preserve ChasmCtx across the swap.
 * Frame state is always discarded (cleared each tick).
 * *   @score: preserved
 *   @high_score: preserved
 */
void chasm_reload_migrate(ChasmCtx *ctx) {
    chasm_clear_frame(ctx);}

