(module
  (global $g_counter (mut i64) (i64.const 0))
  (func $tick (export "tick")
    (local $t0 i64)
    (local $t1 i64)
    (local $t2 i64)
    (local $t3 i64)
    (local $t4 i64)
    (local.set $t0 (global.get $g_counter))
    (local.set $t1 (i64.const 1))
    (local.set $t2 (i64.add (local.get $t0) (local.get $t1)))
    (local.set $t3 (local.get $t2))
    (global.set $g_counter (local.get $t3))
    (local.set $t4 (global.get $g_counter))
    ;; (unsupported instr)
    (return)
  )
  (func $greet (export "greet")
    (local $t0 i64)
    (local.set $t0 (i64.const 42))
    ;; (unsupported instr)
    (return)
  )
)
