/* Generated by Chasm bootstrap compiler - do not edit. */
#include "chasm_rt.h"

/* Forward declarations */
void chasm_test_shape(ChasmCtx *ctx);
void chasm_test_easing(ChasmCtx *ctx);
void chasm_test_vec2(ChasmCtx *ctx);
void chasm_test_bitwise(ChasmCtx *ctx);
void chasm_test_string(ChasmCtx *ctx);
void chasm_test_conversion(ChasmCtx *ctx);
void chasm_test_color(ChasmCtx *ctx);
void chasm_test_time(ChasmCtx *ctx);
void chasm_test_assert(ChasmCtx *ctx);

void chasm_test_shape(ChasmCtx *ctx) {
  chasm_print_f(ctx, chasm_fract(ctx, 3.75));
  chasm_print_f(ctx, chasm_wrap(ctx, 110.0, 0.0, 100.0));
  chasm_print_f(ctx, chasm_snap(ctx, 17.0, 5.0));
  chasm_print_f(ctx, chasm_smooth_step(ctx, 0.0, 1.0, 0.5));
  chasm_print_f(ctx, chasm_ping_pong(ctx, 3.5, 2.0));
  chasm_print_f(ctx, chasm_move_toward(ctx, 0.0, 10.0, 3.0));
  chasm_print_f(ctx, chasm_sign(ctx, -(99.0)));
}

void chasm_test_easing(ChasmCtx *ctx) {
  chasm_print_f(ctx, chasm_ease_in(ctx, 0.5));
  chasm_print_f(ctx, chasm_ease_out(ctx, 0.5));
  chasm_print_f(ctx, chasm_ease_in_out(ctx, 0.5));
  chasm_print_f(ctx, chasm_ease_in_cubic(ctx, 0.5));
  chasm_print_f(ctx, chasm_ease_out_bounce(ctx, 1.0));
}

void chasm_test_vec2(ChasmCtx *ctx) {
  chasm_print_f(ctx, chasm_vec2_len(ctx, 3.0, 4.0));
  chasm_print_f(ctx, chasm_vec2_dot(ctx, 1.0, 0.0, 0.0, 1.0));
  chasm_print_f(ctx, chasm_vec2_dist(ctx, 0.0, 0.0, 3.0, 4.0));
  chasm_print_f(ctx, chasm_vec2_norm_x(ctx, 3.0, 4.0));
  chasm_print_f(ctx, chasm_vec2_norm_y(ctx, 3.0, 4.0));
  chasm_print_f(ctx, chasm_vec2_cross(ctx, 1.0, 0.0, 0.0, 1.0));
}

void chasm_test_bitwise(ChasmCtx *ctx) {
  chasm_print(ctx, chasm_bit_and(ctx, 255, 15));
  chasm_print(ctx, chasm_bit_or(ctx, 240, 15));
  chasm_print(ctx, chasm_bit_xor(ctx, 255, 15));
  chasm_print(ctx, chasm_bit_shl(ctx, 1, 4));
  chasm_print(ctx, chasm_bit_shr(ctx, 256, 4));
}

void chasm_test_string(ChasmCtx *ctx) {
  chasm_print_s(ctx, chasm_str_upper(ctx, "hello"));
  chasm_print_s(ctx, chasm_str_lower(ctx, "WORLD"));
  chasm_print_s(ctx, chasm_str_trim(ctx, "  hi  "));
  chasm_print_s(ctx, chasm_str_repeat(ctx, "ab", 3));
  chasm_print_s(ctx, chasm_str_slice(ctx, "chasm", 1, 4));
  chasm_print(ctx, chasm_str_char_at(ctx, "A", 0));
  chasm_print_s(ctx, chasm_str_from_char(ctx, 65));
  chasm_print_b(ctx, chasm_str_contains(ctx, "hello world", "world"));
  chasm_print_b(ctx, chasm_str_starts_with(ctx, "chasm", "cha"));
  chasm_print_b(ctx, chasm_str_ends_with(ctx, "chasm", "asm"));
  chasm_print_b(ctx, chasm_str_eq(ctx, "abc", "abc"));
  chasm_print_b(ctx, chasm_str_eq(ctx, "abc", "xyz"));
}

void chasm_test_conversion(ChasmCtx *ctx) {
  chasm_print(ctx, chasm_to_int(ctx, 3.9));
  chasm_print_f(ctx, chasm_to_float(ctx, 42));
  chasm_print_b(ctx, chasm_to_bool(ctx, 0));
  chasm_print_b(ctx, chasm_to_bool(ctx, 7));
}

void chasm_test_color(ChasmCtx *ctx) {
  int64_t red = chasm_rgb(ctx, 255, 0, 0);
  chasm_print(ctx, chasm_color_r(ctx, red));
  chasm_print(ctx, chasm_color_g(ctx, red));
  chasm_print(ctx, chasm_color_b(ctx, red));
  chasm_print(ctx, chasm_color_a(ctx, red));
  int64_t white = chasm_rgb(ctx, 255, 255, 255);
  int64_t mixed = chasm_color_lerp(ctx, red, white, 0.5);
  chasm_print(ctx, chasm_color_r(ctx, mixed));
  chasm_print(ctx, chasm_color_g(ctx, mixed));
}

void chasm_test_time(ChasmCtx *ctx) {
  int64_t ms = chasm_time_ms(ctx);
  chasm_print_b(ctx, (ms > 0));
}

void chasm_test_assert(ChasmCtx *ctx) {
  chasm_assert(ctx, (1 == 1));
  chasm_assert_eq(ctx, (2 + 2), 4);
  chasm_print(ctx, 1);
}

