/* Generated by Chasm bootstrap compiler - do not edit. */
#include "chasm_rt.h"

/* Module attributes */
static int64_t g_score;

void chasm_module_init(ChasmCtx *ctx) {
  g_score = 150;
}

void chasm_main(ChasmCtx *ctx) {
  int64_t x = 5;
  if (x > 0) {
    chasm_print_s(ctx, "positive");
  }
  if (x > 0) {
    chasm_print_s(ctx, "positive");
  } else {
    chasm_print_s(ctx, "non-positive");
  }
  if (x > 0) {
    chasm_print_s(ctx, "positive");
  } else {
    if (x < 0) {
      chasm_print_s(ctx, "negative");
    } else {
      chasm_print_s(ctx, "zero");
    }
  }
  const char* label = (g_score > 100 ? "great" : "ok");
  chasm_print_s(ctx, label);
  int64_t i = 0;
  while (i < 3) {
    chasm_print(ctx, i);
    i = (i + 1);
  }
  {
    ChasmArray _iter = chasm_range(ctx, 0, 5);
    int64_t _fi = 0, _fl = _iter.len;
    while (_fi < _fl) {
      int64_t i = chasm_array_get(ctx, &_iter, _fi);
      chasm_print(ctx, i);
      _fi++;
    }
  }
  ChasmArray names = chasm_array_new(ctx, 3);
  chasm_array_push_s(ctx, &names, "Alice");
  chasm_array_push_s(ctx, &names, "Bob");
  chasm_array_push_s(ctx, &names, "Carol");
  {
    ChasmArray _iter = names;
    int64_t _fi = 0, _fl = _iter.len;
    while (_fi < _fl) {
      const char* name = chasm_array_get_s(ctx, &_iter, _fi);
      chasm_print_s(ctx, name);
      _fi++;
    }
  }
  {
    ChasmArray _iter = chasm_range(ctx, 0, 10);
    int64_t _fi = 0, _fl = _iter.len;
    while (_fi < _fl) {
      int64_t i = chasm_array_get(ctx, &_iter, _fi);
      if (i == 3) {
        continue;
      }
      if (i == 6) {
        break;
      }
      chasm_print(ctx, i);
      _fi++;
    }
  }
}

