/* Generated by Chasm bootstrap compiler - do not edit. */
#include "chasm_rt.h"

/* Struct types */
typedef struct {
    double x;
    double y;
} Vec2;

/* Typed array helpers */
static inline Vec2 chasm_array_get_Vec2(ChasmCtx *ctx, ChasmArray *a, int64_t i) {
    static const Vec2 zero = {0};
    if (i < 0 || i >= a->len) return zero;
    return ((Vec2*)a->data)[i];
}
static inline void chasm_array_set_Vec2(ChasmCtx *ctx, ChasmArray *a, int64_t i, Vec2 v) {
    if (i >= 0 && i < a->len) ((Vec2*)a->data)[i] = v;
}
static inline void chasm_array_push_Vec2(ChasmCtx *ctx, ChasmArray *a, Vec2 v) {
    if (a->len >= a->cap) { a->cap = a->cap * 2 + 8; a->data = realloc(a->data, (size_t)a->cap * sizeof(Vec2)); }
    if (a->data) ((Vec2*)a->data)[a->len++] = v;
}
static inline ChasmArray chasm_array_fixed_init_Vec2(ChasmArena *arena, int64_t cap, Vec2 def) {
    if (cap <= 0) cap = 8;
    void *d = chasm_alloc(arena, (size_t)cap * sizeof(Vec2), _Alignof(Vec2));
    if (!d) return (ChasmArray){NULL, 0, cap, (int64_t)sizeof(Vec2)};
    Vec2 *p = (Vec2*)d; for (int64_t _i = 0; _i < cap; _i++) p[_i] = def;
    return (ChasmArray){d, cap, cap, (int64_t)sizeof(Vec2)};
}

/* Forward declarations */
double chasm_length(ChasmCtx *ctx, Vec2);
int64_t chasm_fib(ChasmCtx *ctx, int64_t);

double chasm_length(ChasmCtx *ctx, Vec2 v) {
  chasm_sqrt(ctx, ((v.x * v.x) + (v.y * v.y)));
}

int64_t chasm_fib(ChasmCtx *ctx, int64_t n) {
  if (n <= 1) {
    return n;
  }
  return (chasm_fib(ctx, (n - 1)) + chasm_fib(ctx, (n - 2)));
}

void chasm_main(ChasmCtx *ctx) {
  chasm_print_s(ctx, "Hello, Chasm!");
  const char* name = "world";
  int64_t x = 42;
  const char* msg = chasm_str_concat(ctx, chasm_str_concat(ctx, chasm_str_concat(ctx, "hello ", name), ", x is "), chasm_int_to_str(ctx, x));
  chasm_print_s(ctx, msg);
  chasm_print(ctx, chasm_fib(ctx, 10));
  Vec2 pos = (Vec2){ .x = 3.0, .y = 4.0 };
  chasm_print_f(ctx, chasm_length(ctx, pos));
  Vec2 pos2 = (Vec2){ .x = 0.0, .y = pos.y };
  chasm_print_f(ctx, pos2.y);
  ChasmArray scores = chasm_array_new(ctx, 4);
  chasm_array_push(ctx, &scores, 100);
  chasm_array_push(ctx, &scores, 85);
  chasm_array_push(ctx, &scores, 92);
  chasm_print(ctx, scores.len);
  chasm_print(ctx, scores.cap);
  chasm_print(ctx, chasm_array_get(ctx, &scores, 0));
  int64_t total = 0;
  {
    ChasmArray _iter = chasm_range(ctx, 0, scores.len);
    int64_t _fi = 0, _fl = _iter.len;
    while (_fi < _fl) {
      int64_t i = chasm_array_get(ctx, &_iter, _fi);
      total = (total + chasm_array_get(ctx, &scores, i));
      _fi++;
    }
  }
  chasm_print(ctx, total);
}

