/* Generated by Chasm bootstrap compiler - do not edit. */
#include "chasm_rt.h"

/* Forward declarations */
int64_t chasm_screen_w(ChasmCtx *ctx);
int64_t chasm_screen_h(ChasmCtx *ctx);
void chasm_set_fps(ChasmCtx *ctx, int64_t);
void chasm_set_title(ChasmCtx *ctx, const char*);
int64_t chasm_fps(ChasmCtx *ctx);
double chasm_dt(ChasmCtx *ctx);
double chasm_time(ChasmCtx *ctx);
void chasm_clear(ChasmCtx *ctx, int64_t);
void chasm_draw_rect(ChasmCtx *ctx, double, double, double, double, int64_t);
void chasm_draw_rect_lines(ChasmCtx *ctx, double, double, double, double, int64_t);
void chasm_draw_rect_rounded(ChasmCtx *ctx, double, double, double, double, double, int64_t, int64_t);
void chasm_draw_circle(ChasmCtx *ctx, double, double, double, int64_t);
void chasm_draw_circle_lines(ChasmCtx *ctx, double, double, double, int64_t);
void chasm_draw_line(ChasmCtx *ctx, double, double, double, double, int64_t);
void chasm_draw_line_ex(ChasmCtx *ctx, double, double, double, double, double, int64_t);
void chasm_draw_text(ChasmCtx *ctx, const char*, double, double, int64_t, int64_t);
double chasm_measure_text(ChasmCtx *ctx, const char*, int64_t);
void chasm_draw_fps(ChasmCtx *ctx, double, double);
int64_t chasm_load_texture(ChasmCtx *ctx, const char*);
void chasm_unload_texture(ChasmCtx *ctx, int64_t);
void chasm_draw_texture(ChasmCtx *ctx, int64_t, double, double, int64_t);
void chasm_draw_texture_ex(ChasmCtx *ctx, int64_t, double, double, double, double, int64_t);
void chasm_draw_texture_rect(ChasmCtx *ctx, int64_t, double, double, double, double, double, double, int64_t);
int64_t chasm_texture_w(ChasmCtx *ctx, int64_t);
int64_t chasm_texture_h(ChasmCtx *ctx, int64_t);
int64_t chasm_load_font(ChasmCtx *ctx, const char*);
void chasm_draw_text_ex(ChasmCtx *ctx, int64_t, const char*, double, double, double, double, int64_t);
void chasm_init_audio(ChasmCtx *ctx);
void chasm_close_audio(ChasmCtx *ctx);
int64_t chasm_load_sound(ChasmCtx *ctx, const char*);
void chasm_play_sound(ChasmCtx *ctx, int64_t);
void chasm_stop_sound(ChasmCtx *ctx, int64_t);
int64_t chasm_load_music(ChasmCtx *ctx, const char*);
void chasm_play_music(ChasmCtx *ctx, int64_t);
void chasm_update_music(ChasmCtx *ctx, int64_t);
void chasm_stop_music(ChasmCtx *ctx, int64_t);
bool chasm_key_down(ChasmCtx *ctx, int64_t);
bool chasm_key_pressed(ChasmCtx *ctx, int64_t);
bool chasm_key_released(ChasmCtx *ctx, int64_t);
bool chasm_key_up(ChasmCtx *ctx, int64_t);
int64_t chasm_key_last(ChasmCtx *ctx);
double chasm_mouse_x(ChasmCtx *ctx);
double chasm_mouse_y(ChasmCtx *ctx);
double chasm_mouse_dx(ChasmCtx *ctx);
double chasm_mouse_dy(ChasmCtx *ctx);
bool chasm_mouse_down(ChasmCtx *ctx, int64_t);
bool chasm_mouse_pressed(ChasmCtx *ctx, int64_t);
bool chasm_mouse_released(ChasmCtx *ctx, int64_t);
double chasm_mouse_wheel(ChasmCtx *ctx);
void chasm_hide_cursor(ChasmCtx *ctx);
void chasm_show_cursor(ChasmCtx *ctx);
bool chasm_sound_playing(ChasmCtx *ctx, int64_t);
void chasm_sound_volume(ChasmCtx *ctx, int64_t, double);
void chasm_sound_pitch(ChasmCtx *ctx, int64_t, double);
void chasm_pause_sound(ChasmCtx *ctx, int64_t);
void chasm_resume_sound(ChasmCtx *ctx, int64_t);
bool chasm_music_playing(ChasmCtx *ctx, int64_t);
void chasm_music_volume(ChasmCtx *ctx, int64_t, double);
void chasm_music_pitch(ChasmCtx *ctx, int64_t, double);
double chasm_music_length(ChasmCtx *ctx, int64_t);
double chasm_music_played(ChasmCtx *ctx, int64_t);
void chasm_pause_music(ChasmCtx *ctx, int64_t);
void chasm_resume_music(ChasmCtx *ctx, int64_t);
bool chasm_window_resized(ChasmCtx *ctx);
void chasm_set_window_size(ChasmCtx *ctx, int64_t, int64_t);
void chasm_toggle_fullscreen(ChasmCtx *ctx);
bool chasm_is_fullscreen(ChasmCtx *ctx);
bool chasm_window_focused(ChasmCtx *ctx);
void chasm_draw_triangle(ChasmCtx *ctx, double, double, double, double, double, double, int64_t);
void chasm_draw_triangle_lines(ChasmCtx *ctx, double, double, double, double, double, double, int64_t);
void chasm_draw_ellipse(ChasmCtx *ctx, double, double, double, double, int64_t);
void chasm_draw_ring(ChasmCtx *ctx, double, double, double, double, double, double, int64_t, int64_t);
void chasm_draw_poly(ChasmCtx *ctx, double, double, int64_t, double, double, int64_t);
void chasm_draw_texture_tiled(ChasmCtx *ctx, int64_t, double, double, double, double, double, double, double, double, int64_t);
void chasm_set_texture_filter(ChasmCtx *ctx, int64_t, int64_t);
void chasm_camera2d_begin(ChasmCtx *ctx, double, double, double, double, double, double);
void chasm_camera2d_end(ChasmCtx *ctx);
double chasm_world_to_screen_x(ChasmCtx *ctx, double, double, double, double, double, double, double, double);
double chasm_world_to_screen_y(ChasmCtx *ctx, double, double, double, double, double, double, double, double);
bool chasm_gamepad_available(ChasmCtx *ctx, int64_t);
bool chasm_gamepad_button_down(ChasmCtx *ctx, int64_t, int64_t);
bool chasm_gamepad_button_pressed(ChasmCtx *ctx, int64_t, int64_t);
double chasm_gamepad_axis(ChasmCtx *ctx, int64_t, int64_t);
void chasm_set_mouse_pos(ChasmCtx *ctx, double, double);
void chasm_mouse_cursor(ChasmCtx *ctx, int64_t);
const char* chasm_get_clipboard(ChasmCtx *ctx);
void chasm_set_clipboard(ChasmCtx *ctx, const char*);
bool chasm_collide_rects(ChasmCtx *ctx, double, double, double, double, double, double, double, double);
bool chasm_collide_circles(ChasmCtx *ctx, double, double, double, double, double, double);
bool chasm_point_in_rect(ChasmCtx *ctx, double, double, double, double, double, double);
void chasm_clear_background(ChasmCtx *ctx, int64_t);
void chasm_draw_rectangle(ChasmCtx *ctx, double, double, double, double, int64_t);
void chasm_draw_rectangle_lines(ChasmCtx *ctx, double, double, double, double, int64_t);
void chasm_draw_circle_v(ChasmCtx *ctx, double, double, double, int64_t);
int64_t chasm_screen_width(ChasmCtx *ctx);
int64_t chasm_screen_height(ChasmCtx *ctx);
double chasm_rand_range(ChasmCtx *ctx, double, double);
void chasm_on_init(ChasmCtx *ctx);
void chasm_on_tick(ChasmCtx *ctx, double);
void chasm_on_draw(ChasmCtx *ctx);

/* Module attributes */
static double g_player_x;
static double g_player_y;
static double g_speed;

void chasm_module_init(ChasmCtx *ctx) {
  g_player_x = 400.0;
  g_player_y = 300.0;
  g_speed = 200.0;
}

void chasm_on_init(ChasmCtx *ctx) {
}

void chasm_on_tick(ChasmCtx *ctx, double dt) {
  if (chasm_key_down(ctx, "right")) {
    g_player_x = (g_player_x + (g_speed * dt));
  }
  if (chasm_key_down(ctx, "left")) {
    g_player_x = (g_player_x - (g_speed * dt));
  }
  if (chasm_key_down(ctx, "down")) {
    g_player_y = (g_player_y + (g_speed * dt));
  }
  if (chasm_key_down(ctx, "up")) {
    g_player_y = (g_player_y - (g_speed * dt));
  }
}

void chasm_on_draw(ChasmCtx *ctx) {
  chasm_clear_background(ctx, 0x181820ff);
  chasm_draw_rectangle(ctx, (g_player_x - 16.0), (g_player_y - 16.0), 32.0, 32.0, 0x4488ffff);
  chasm_draw_text(ctx, "Move with arrow keys", 10, 10, 20, 0xffffffff);
}

