/* Generated by Chasm bootstrap compiler - do not edit. */
#include "chasm_rt.h"

/* Struct types */
typedef struct {
    double x;
    double y;
    double vx;
    double vy;
    int64_t active;
} Bullet;

/* Typed array helpers */
static inline Bullet chasm_array_get_Bullet(ChasmCtx *ctx, ChasmArray *a, int64_t i) {
    static const Bullet zero = {0};
    if (i < 0 || i >= a->len) return zero;
    return ((Bullet*)a->data)[i];
}
static inline void chasm_array_set_Bullet(ChasmCtx *ctx, ChasmArray *a, int64_t i, Bullet v) {
    if (i >= 0 && i < a->len) ((Bullet*)a->data)[i] = v;
}
static inline void chasm_array_push_Bullet(ChasmCtx *ctx, ChasmArray *a, Bullet v) {
    if (a->len >= a->cap) { a->cap = a->cap * 2 + 8; a->data = realloc(a->data, (size_t)a->cap * sizeof(Bullet)); }
    if (a->data) ((Bullet*)a->data)[a->len++] = v;
}
static inline ChasmArray chasm_array_fixed_init_Bullet(ChasmArena *arena, int64_t cap, Bullet def) {
    if (cap <= 0) cap = 8;
    void *d = chasm_alloc(arena, (size_t)cap * sizeof(Bullet), _Alignof(Bullet));
    if (!d) return (ChasmArray){NULL, 0, cap, (int64_t)sizeof(Bullet)};
    Bullet *p = (Bullet*)d; for (int64_t _i = 0; _i < cap; _i++) p[_i] = def;
    return (ChasmArray){d, cap, cap, (int64_t)sizeof(Bullet)};
}

/* Forward declarations */
int64_t chasm_screen_w(ChasmCtx *ctx);
int64_t chasm_screen_h(ChasmCtx *ctx);
void chasm_set_fps(ChasmCtx *ctx, int64_t);
void chasm_set_title(ChasmCtx *ctx, const char*);
int64_t chasm_fps(ChasmCtx *ctx);
double chasm_dt(ChasmCtx *ctx);
double chasm_time(ChasmCtx *ctx);
void chasm_clear(ChasmCtx *ctx, int64_t);
void chasm_draw_rect(ChasmCtx *ctx, double, double, double, double, int64_t);
void chasm_draw_rect_lines(ChasmCtx *ctx, double, double, double, double, int64_t);
void chasm_draw_rect_rounded(ChasmCtx *ctx, double, double, double, double, double, int64_t, int64_t);
void chasm_draw_circle(ChasmCtx *ctx, double, double, double, int64_t);
void chasm_draw_circle_lines(ChasmCtx *ctx, double, double, double, int64_t);
void chasm_draw_line(ChasmCtx *ctx, double, double, double, double, int64_t);
void chasm_draw_line_ex(ChasmCtx *ctx, double, double, double, double, double, int64_t);
void chasm_draw_text(ChasmCtx *ctx, const char*, double, double, int64_t, int64_t);
double chasm_measure_text(ChasmCtx *ctx, const char*, int64_t);
void chasm_draw_fps(ChasmCtx *ctx, double, double);
int64_t chasm_load_texture(ChasmCtx *ctx, const char*);
void chasm_unload_texture(ChasmCtx *ctx, int64_t);
void chasm_draw_texture(ChasmCtx *ctx, int64_t, double, double, int64_t);
void chasm_draw_texture_ex(ChasmCtx *ctx, int64_t, double, double, double, double, int64_t);
void chasm_draw_texture_rect(ChasmCtx *ctx, int64_t, double, double, double, double, double, double, int64_t);
int64_t chasm_texture_w(ChasmCtx *ctx, int64_t);
int64_t chasm_texture_h(ChasmCtx *ctx, int64_t);
int64_t chasm_load_font(ChasmCtx *ctx, const char*);
void chasm_draw_text_ex(ChasmCtx *ctx, int64_t, const char*, double, double, double, double, int64_t);
void chasm_init_audio(ChasmCtx *ctx);
void chasm_close_audio(ChasmCtx *ctx);
int64_t chasm_load_sound(ChasmCtx *ctx, const char*);
void chasm_play_sound(ChasmCtx *ctx, int64_t);
void chasm_stop_sound(ChasmCtx *ctx, int64_t);
int64_t chasm_load_music(ChasmCtx *ctx, const char*);
void chasm_play_music(ChasmCtx *ctx, int64_t);
void chasm_update_music(ChasmCtx *ctx, int64_t);
void chasm_stop_music(ChasmCtx *ctx, int64_t);
bool chasm_key_down(ChasmCtx *ctx, int64_t);
bool chasm_key_pressed(ChasmCtx *ctx, int64_t);
bool chasm_key_released(ChasmCtx *ctx, int64_t);
bool chasm_key_up(ChasmCtx *ctx, int64_t);
int64_t chasm_key_last(ChasmCtx *ctx);
double chasm_mouse_x(ChasmCtx *ctx);
double chasm_mouse_y(ChasmCtx *ctx);
double chasm_mouse_dx(ChasmCtx *ctx);
double chasm_mouse_dy(ChasmCtx *ctx);
bool chasm_mouse_down(ChasmCtx *ctx, int64_t);
bool chasm_mouse_pressed(ChasmCtx *ctx, int64_t);
bool chasm_mouse_released(ChasmCtx *ctx, int64_t);
double chasm_mouse_wheel(ChasmCtx *ctx);
void chasm_hide_cursor(ChasmCtx *ctx);
void chasm_show_cursor(ChasmCtx *ctx);
bool chasm_sound_playing(ChasmCtx *ctx, int64_t);
void chasm_sound_volume(ChasmCtx *ctx, int64_t, double);
void chasm_sound_pitch(ChasmCtx *ctx, int64_t, double);
void chasm_pause_sound(ChasmCtx *ctx, int64_t);
void chasm_resume_sound(ChasmCtx *ctx, int64_t);
bool chasm_music_playing(ChasmCtx *ctx, int64_t);
void chasm_music_volume(ChasmCtx *ctx, int64_t, double);
void chasm_music_pitch(ChasmCtx *ctx, int64_t, double);
double chasm_music_length(ChasmCtx *ctx, int64_t);
double chasm_music_played(ChasmCtx *ctx, int64_t);
void chasm_pause_music(ChasmCtx *ctx, int64_t);
void chasm_resume_music(ChasmCtx *ctx, int64_t);
bool chasm_window_resized(ChasmCtx *ctx);
void chasm_set_window_size(ChasmCtx *ctx, int64_t, int64_t);
void chasm_toggle_fullscreen(ChasmCtx *ctx);
bool chasm_is_fullscreen(ChasmCtx *ctx);
bool chasm_window_focused(ChasmCtx *ctx);
void chasm_draw_triangle(ChasmCtx *ctx, double, double, double, double, double, double, int64_t);
void chasm_draw_triangle_lines(ChasmCtx *ctx, double, double, double, double, double, double, int64_t);
void chasm_draw_ellipse(ChasmCtx *ctx, double, double, double, double, int64_t);
void chasm_draw_ring(ChasmCtx *ctx, double, double, double, double, double, double, int64_t, int64_t);
void chasm_draw_poly(ChasmCtx *ctx, double, double, int64_t, double, double, int64_t);
void chasm_draw_texture_tiled(ChasmCtx *ctx, int64_t, double, double, double, double, double, double, double, double, int64_t);
void chasm_set_texture_filter(ChasmCtx *ctx, int64_t, int64_t);
void chasm_camera2d_begin(ChasmCtx *ctx, double, double, double, double, double, double);
void chasm_camera2d_end(ChasmCtx *ctx);
double chasm_world_to_screen_x(ChasmCtx *ctx, double, double, double, double, double, double, double, double);
double chasm_world_to_screen_y(ChasmCtx *ctx, double, double, double, double, double, double, double, double);
bool chasm_gamepad_available(ChasmCtx *ctx, int64_t);
bool chasm_gamepad_button_down(ChasmCtx *ctx, int64_t, int64_t);
bool chasm_gamepad_button_pressed(ChasmCtx *ctx, int64_t, int64_t);
double chasm_gamepad_axis(ChasmCtx *ctx, int64_t, int64_t);
void chasm_set_mouse_pos(ChasmCtx *ctx, double, double);
void chasm_mouse_cursor(ChasmCtx *ctx, int64_t);
const char* chasm_get_clipboard(ChasmCtx *ctx);
void chasm_set_clipboard(ChasmCtx *ctx, const char*);
bool chasm_collide_rects(ChasmCtx *ctx, double, double, double, double, double, double, double, double);
bool chasm_collide_circles(ChasmCtx *ctx, double, double, double, double, double, double);
bool chasm_point_in_rect(ChasmCtx *ctx, double, double, double, double, double, double);
void chasm_clear_background(ChasmCtx *ctx, int64_t);
void chasm_draw_rectangle(ChasmCtx *ctx, double, double, double, double, int64_t);
void chasm_draw_rectangle_lines(ChasmCtx *ctx, double, double, double, double, int64_t);
void chasm_draw_circle_v(ChasmCtx *ctx, double, double, double, int64_t);
int64_t chasm_screen_width(ChasmCtx *ctx);
int64_t chasm_screen_height(ChasmCtx *ctx);
double chasm_rand_range(ChasmCtx *ctx, double, double);
void chasm_spawn_bullet(ChasmCtx *ctx, double, double, double, double);
void chasm_update_bullets(ChasmCtx *ctx, double);
void chasm_on_tick(ChasmCtx *ctx, double);
void chasm_on_draw(ChasmCtx *ctx);

#ifndef CHASM_ARRAY_FIXED_HELPERS_DEFINED
#define CHASM_ARRAY_FIXED_HELPERS_DEFINED
/* Arena-backed array helpers for @attr arrays */
/* array_fixed_in: allocates data from arena at fixed capacity — never grows. */
static inline ChasmArray chasm_array_fixed_in(ChasmArena *arena, int64_t cap) {
    if (cap <= 0) cap = 8;
    void *d = chasm_alloc(arena, (size_t)cap * 8, 8);
    if (!d) return (ChasmArray){NULL, 0, 0};
    return (ChasmArray){d, 0, cap};
}
/* push_fixed: bounds-checked push — aborts on overflow (no realloc). */
static inline void chasm_array_push_fixed(ChasmCtx *ctx, ChasmArray *a, int64_t v) {
    (void)ctx;
    if (a->len >= a->cap) { fprintf(stderr, "chasm: array_fixed overflow (cap=%lld)\n", (long long)a->cap); abort(); }
    ((int64_t*)a->data)[a->len++] = v;
}
/* array_fixed_in_f / push_fixed_f / get_f / set_f: float (double) element variants. */
static inline ChasmArray chasm_array_fixed_in_f(ChasmArena *arena, int64_t cap) {
    if (cap <= 0) cap = 8;
    void *d = chasm_alloc(arena, (size_t)cap * sizeof(double), 8);
    if (!d) return (ChasmArray){NULL, 0, 0};
    return (ChasmArray){d, 0, cap};
}
static inline void chasm_array_push_fixed_f(ChasmCtx *ctx, ChasmArray *a, double v) {
    (void)ctx;
    if (a->len >= a->cap) { fprintf(stderr, "chasm: array_fixed overflow (cap=%lld)\n", (long long)a->cap); abort(); }
    ((double*)a->data)[a->len++] = v;
}
static inline double chasm_array_get_f(ChasmCtx *ctx, ChasmArray *a, int64_t i) {
    (void)ctx; if (i < 0 || i >= a->len) return 0.0;
    return ((double*)a->data)[i];
}
static inline void chasm_array_set_f(ChasmCtx *ctx, ChasmArray *a, int64_t i, double v) {
    (void)ctx; if (i >= 0 && i < a->len) ((double*)a->data)[i] = v;
}
/* array_new_in: arena-backed growable array (bump-copy on growth). */
static inline ChasmArray chasm_array_new_in(ChasmArena *arena, int64_t cap) {
    if (cap <= 0) cap = 8;
    void *d = chasm_alloc(arena, (size_t)cap * 8, 8);
    if (!d) return (ChasmArray){NULL, 0, 0};
    return (ChasmArray){d, 0, cap};
}
static inline void chasm_array_push_in(ChasmArena *arena, ChasmArray *a, int64_t v) {
    if (a->len >= a->cap) {
        int64_t new_cap = a->cap * 2 + 8;
        void *nd = chasm_alloc(arena, (size_t)new_cap * 8, 8);
        if (nd && a->data) memcpy(nd, a->data, (size_t)a->len * 8);
        a->data = nd; a->cap = new_cap;
    }
    if (a->data) ((int64_t*)a->data)[a->len++] = v;
}
#endif /* CHASM_ARRAY_FIXED_HELPERS_DEFINED */

/* Module attributes */
static ChasmArray g_bullets;
static double g_player_x;
static double g_player_y;
static double g_fire_timer;

void chasm_module_init(ChasmCtx *ctx) {
  g_bullets = chasm_array_fixed_init_Bullet(&ctx->script, 128, (Bullet){ .x = 0.0, .y = 0.0, .vx = 0.0, .vy = 0.0, .active = 0 });
  g_player_x = 400.0;
  g_player_y = 500.0;
  g_fire_timer = 0.0;
}

void chasm_spawn_bullet(ChasmCtx *ctx, double x, double y, double vx, double vy) {
  int64_t i = 0;
  while (i < g_bullets.len) {
    Bullet b = chasm_array_get_Bullet(ctx, &g_bullets, i);
    if (b.active == 0) {
      chasm_array_set_Bullet(ctx, &g_bullets, i, (Bullet){ .x = x, .y = y, .vx = vx, .vy = vy, .active = 1 });
      return 0;
    }
    i = (i + 1);
  }
  return 0;
}

void chasm_update_bullets(ChasmCtx *ctx, double dt) {
  int64_t i = 0;
  while (i < g_bullets.len) {
    Bullet b = chasm_array_get_Bullet(ctx, &g_bullets, i);
    if (b.active == 1) {
      b = (Bullet){ .x = (b.x + (b.vx * dt)), .y = (b.y + (b.vy * dt)), .vx = b.vx, .vy = b.vy, .active = b.active };
      if (b.y < 0.0) {
        b = (Bullet){ .x = b.x, .y = b.y, .vx = b.vx, .vy = b.vy, .active = 0 };
      }
      chasm_array_set_Bullet(ctx, &g_bullets, i, b);
    }
    i = (i + 1);
  }
}

void chasm_on_tick(ChasmCtx *ctx, double dt) {
  if (chasm_key_down(ctx, "left")) {
    g_player_x = (g_player_x - (300.0 * dt));
  }
  if (chasm_key_down(ctx, "right")) {
    g_player_x = (g_player_x + (300.0 * dt));
  }
  g_fire_timer = (g_fire_timer - dt);
  if (chasm_key_down(ctx, "space") && (g_fire_timer <= 0.0)) {
    chasm_spawn_bullet(ctx, g_player_x, g_player_y, 0.0, -(600.0));
    g_fire_timer = 0.1;
  }
  chasm_update_bullets(ctx, dt);
}

void chasm_on_draw(ChasmCtx *ctx) {
  chasm_clear_background(ctx, 0x101018ff);
  chasm_draw_rectangle(ctx, (g_player_x - 12.0), (g_player_y - 8.0), 24.0, 16.0, 0x44aaffff);
  int64_t i = 0;
  while (i < g_bullets.len) {
    Bullet b = chasm_array_get_Bullet(ctx, &g_bullets, i);
    if (b.active == 1) {
      chasm_draw_rectangle(ctx, (b.x - 3.0), (b.y - 6.0), 6.0, 12.0, 0xffff00ff);
    }
    i = (i + 1);
  }
}

