/* Generated by Chasm bootstrap compiler - do not edit. */
#include "chasm_rt.h"

/* Struct types */
typedef struct {
    double x;
    double y;
    const char* state;
    double inv_timer;
} Player;

/* Typed array helpers */
static inline Player chasm_array_get_Player(ChasmCtx *ctx, ChasmArray *a, int64_t i) {
    static const Player zero = {0};
    if (i < 0 || i >= a->len) return zero;
    return ((Player*)a->data)[i];
}
static inline void chasm_array_set_Player(ChasmCtx *ctx, ChasmArray *a, int64_t i, Player v) {
    if (i >= 0 && i < a->len) ((Player*)a->data)[i] = v;
}
static inline void chasm_array_push_Player(ChasmCtx *ctx, ChasmArray *a, Player v) {
    if (a->len >= a->cap) { a->cap = a->cap * 2 + 8; a->data = realloc(a->data, (size_t)a->cap * sizeof(Player)); }
    if (a->data) ((Player*)a->data)[a->len++] = v;
}
static inline ChasmArray chasm_array_fixed_init_Player(ChasmArena *arena, int64_t cap, Player def) {
    if (cap <= 0) cap = 8;
    void *d = chasm_alloc(arena, (size_t)cap * sizeof(Player), _Alignof(Player));
    if (!d) return (ChasmArray){NULL, 0, cap, (int64_t)sizeof(Player)};
    Player *p = (Player*)d; for (int64_t _i = 0; _i < cap; _i++) p[_i] = def;
    return (ChasmArray){d, cap, cap, (int64_t)sizeof(Player)};
}

/* Forward declarations */
int64_t chasm_screen_w(ChasmCtx *ctx);
int64_t chasm_screen_h(ChasmCtx *ctx);
void chasm_set_fps(ChasmCtx *ctx, int64_t);
void chasm_set_title(ChasmCtx *ctx, const char*);
int64_t chasm_fps(ChasmCtx *ctx);
double chasm_dt(ChasmCtx *ctx);
double chasm_time(ChasmCtx *ctx);
void chasm_clear(ChasmCtx *ctx, int64_t);
void chasm_draw_rect(ChasmCtx *ctx, double, double, double, double, int64_t);
void chasm_draw_rect_lines(ChasmCtx *ctx, double, double, double, double, int64_t);
void chasm_draw_rect_rounded(ChasmCtx *ctx, double, double, double, double, double, int64_t, int64_t);
void chasm_draw_circle(ChasmCtx *ctx, double, double, double, int64_t);
void chasm_draw_circle_lines(ChasmCtx *ctx, double, double, double, int64_t);
void chasm_draw_line(ChasmCtx *ctx, double, double, double, double, int64_t);
void chasm_draw_line_ex(ChasmCtx *ctx, double, double, double, double, double, int64_t);
void chasm_draw_text(ChasmCtx *ctx, const char*, double, double, int64_t, int64_t);
double chasm_measure_text(ChasmCtx *ctx, const char*, int64_t);
void chasm_draw_fps(ChasmCtx *ctx, double, double);
int64_t chasm_load_texture(ChasmCtx *ctx, const char*);
void chasm_unload_texture(ChasmCtx *ctx, int64_t);
void chasm_draw_texture(ChasmCtx *ctx, int64_t, double, double, int64_t);
void chasm_draw_texture_ex(ChasmCtx *ctx, int64_t, double, double, double, double, int64_t);
void chasm_draw_texture_rect(ChasmCtx *ctx, int64_t, double, double, double, double, double, double, int64_t);
int64_t chasm_texture_w(ChasmCtx *ctx, int64_t);
int64_t chasm_texture_h(ChasmCtx *ctx, int64_t);
int64_t chasm_load_font(ChasmCtx *ctx, const char*);
void chasm_draw_text_ex(ChasmCtx *ctx, int64_t, const char*, double, double, double, double, int64_t);
void chasm_init_audio(ChasmCtx *ctx);
void chasm_close_audio(ChasmCtx *ctx);
int64_t chasm_load_sound(ChasmCtx *ctx, const char*);
void chasm_play_sound(ChasmCtx *ctx, int64_t);
void chasm_stop_sound(ChasmCtx *ctx, int64_t);
int64_t chasm_load_music(ChasmCtx *ctx, const char*);
void chasm_play_music(ChasmCtx *ctx, int64_t);
void chasm_update_music(ChasmCtx *ctx, int64_t);
void chasm_stop_music(ChasmCtx *ctx, int64_t);
bool chasm_key_down(ChasmCtx *ctx, int64_t);
bool chasm_key_pressed(ChasmCtx *ctx, int64_t);
bool chasm_key_released(ChasmCtx *ctx, int64_t);
bool chasm_key_up(ChasmCtx *ctx, int64_t);
int64_t chasm_key_last(ChasmCtx *ctx);
double chasm_mouse_x(ChasmCtx *ctx);
double chasm_mouse_y(ChasmCtx *ctx);
double chasm_mouse_dx(ChasmCtx *ctx);
double chasm_mouse_dy(ChasmCtx *ctx);
bool chasm_mouse_down(ChasmCtx *ctx, int64_t);
bool chasm_mouse_pressed(ChasmCtx *ctx, int64_t);
bool chasm_mouse_released(ChasmCtx *ctx, int64_t);
double chasm_mouse_wheel(ChasmCtx *ctx);
void chasm_hide_cursor(ChasmCtx *ctx);
void chasm_show_cursor(ChasmCtx *ctx);
bool chasm_sound_playing(ChasmCtx *ctx, int64_t);
void chasm_sound_volume(ChasmCtx *ctx, int64_t, double);
void chasm_sound_pitch(ChasmCtx *ctx, int64_t, double);
void chasm_pause_sound(ChasmCtx *ctx, int64_t);
void chasm_resume_sound(ChasmCtx *ctx, int64_t);
bool chasm_music_playing(ChasmCtx *ctx, int64_t);
void chasm_music_volume(ChasmCtx *ctx, int64_t, double);
void chasm_music_pitch(ChasmCtx *ctx, int64_t, double);
double chasm_music_length(ChasmCtx *ctx, int64_t);
double chasm_music_played(ChasmCtx *ctx, int64_t);
void chasm_pause_music(ChasmCtx *ctx, int64_t);
void chasm_resume_music(ChasmCtx *ctx, int64_t);
bool chasm_window_resized(ChasmCtx *ctx);
void chasm_set_window_size(ChasmCtx *ctx, int64_t, int64_t);
void chasm_toggle_fullscreen(ChasmCtx *ctx);
bool chasm_is_fullscreen(ChasmCtx *ctx);
bool chasm_window_focused(ChasmCtx *ctx);
void chasm_draw_triangle(ChasmCtx *ctx, double, double, double, double, double, double, int64_t);
void chasm_draw_triangle_lines(ChasmCtx *ctx, double, double, double, double, double, double, int64_t);
void chasm_draw_ellipse(ChasmCtx *ctx, double, double, double, double, int64_t);
void chasm_draw_ring(ChasmCtx *ctx, double, double, double, double, double, double, int64_t, int64_t);
void chasm_draw_poly(ChasmCtx *ctx, double, double, int64_t, double, double, int64_t);
void chasm_draw_texture_tiled(ChasmCtx *ctx, int64_t, double, double, double, double, double, double, double, double, int64_t);
void chasm_set_texture_filter(ChasmCtx *ctx, int64_t, int64_t);
void chasm_camera2d_begin(ChasmCtx *ctx, double, double, double, double, double, double);
void chasm_camera2d_end(ChasmCtx *ctx);
double chasm_world_to_screen_x(ChasmCtx *ctx, double, double, double, double, double, double, double, double);
double chasm_world_to_screen_y(ChasmCtx *ctx, double, double, double, double, double, double, double, double);
bool chasm_gamepad_available(ChasmCtx *ctx, int64_t);
bool chasm_gamepad_button_down(ChasmCtx *ctx, int64_t, int64_t);
bool chasm_gamepad_button_pressed(ChasmCtx *ctx, int64_t, int64_t);
double chasm_gamepad_axis(ChasmCtx *ctx, int64_t, int64_t);
void chasm_set_mouse_pos(ChasmCtx *ctx, double, double);
void chasm_mouse_cursor(ChasmCtx *ctx, int64_t);
const char* chasm_get_clipboard(ChasmCtx *ctx);
void chasm_set_clipboard(ChasmCtx *ctx, const char*);
bool chasm_collide_rects(ChasmCtx *ctx, double, double, double, double, double, double, double, double);
bool chasm_collide_circles(ChasmCtx *ctx, double, double, double, double, double, double);
bool chasm_point_in_rect(ChasmCtx *ctx, double, double, double, double, double, double);
void chasm_clear_background(ChasmCtx *ctx, int64_t);
void chasm_draw_rectangle(ChasmCtx *ctx, double, double, double, double, int64_t);
void chasm_draw_rectangle_lines(ChasmCtx *ctx, double, double, double, double, int64_t);
void chasm_draw_circle_v(ChasmCtx *ctx, double, double, double, int64_t);
int64_t chasm_screen_width(ChasmCtx *ctx);
int64_t chasm_screen_height(ChasmCtx *ctx);
double chasm_rand_range(ChasmCtx *ctx, double, double);
Player chasm_take_hit(ChasmCtx *ctx, Player);
void chasm_on_tick(ChasmCtx *ctx, double);
void chasm_on_draw(ChasmCtx *ctx);

/* Module attributes */
static Player g_player;
static int64_t g_high_score;
static int64_t g_score;
static double g_speed;

void chasm_module_init(ChasmCtx *ctx) {
  g_player = (Player){ .x = 400.0, .y = 300.0, .state = "normal", .inv_timer = 0.0 };
  g_high_score = 0;
  g_score = 0;
  g_speed = 200.0;
}

Player chasm_take_hit(ChasmCtx *ctx, Player p) {
  if (strcmp(p.state, "normal") == 0) {
    return (Player){ .x = p.x, .y = p.y, .state = "invincible", .inv_timer = 1.5 };
  }
  return p;
}

void chasm_on_tick(ChasmCtx *ctx, double dt) {
  Player p = g_player;
  double dx = 0.0;
  double dy = 0.0;
  if (chasm_key_down(ctx, "right")) {
    dx = g_speed;
  }
  if (chasm_key_down(ctx, "left")) {
    dx = -(g_speed);
  }
  if (chasm_key_down(ctx, "up")) {
    dy = -(g_speed);
  }
  if (chasm_key_down(ctx, "down")) {
    dy = g_speed;
  }
  p = (Player){ .x = (p.x + (dx * dt)), .y = (p.y + (dy * dt)), .state = p.state, .inv_timer = p.inv_timer };
  if (strcmp(p.state, "invincible") == 0) {
    p = (Player){ .x = p.x, .y = p.y, .state = p.state, .inv_timer = (p.inv_timer - dt) };
    if (p.inv_timer <= 0.0) {
      p = (Player){ .x = p.x, .y = p.y, .state = "normal", .inv_timer = 0.0 };
    }
  }
  if (chasm_key_pressed(ctx, "space")) {
    p = chasm_take_hit(ctx, p);
  }
  g_player = p;
  g_score = (g_score + 1);
  if (g_score > g_high_score) {
    g_high_score = chasm_persist_copy(ctx, g_score);
  }
}

void chasm_on_draw(ChasmCtx *ctx) {
  chasm_clear_background(ctx, 0x181820ff);
  int64_t col = 0x44aaffff;
  if (strcmp(g_player.state, "invincible") == 0) {
    col = 0xff8800ff;
  }
  chasm_draw_rectangle(ctx, (g_player.x - 16.0), (g_player.y - 16.0), 32.0, 32.0, col);
  chasm_draw_text(ctx, chasm_str_concat(ctx, "Score: ", chasm_int_to_str(ctx, g_score)), 10, 10, 20, 0xffffffff);
  chasm_draw_text(ctx, chasm_str_concat(ctx, "State: ", chasm_int_to_str(ctx, g_player.state)), 10, 35, 20, 0xffffffff);
}

