/* Generated by Chasm bootstrap compiler - do not edit. */
#include "chasm_rt.h"

void chasm_main(ChasmCtx *ctx) {
  const char* greeting = "Hello, world!";
  const char* name = "Chasm";
  int64_t score = 42;
  const char* msg = chasm_str_concat(ctx, chasm_str_concat(ctx, name, " score: "), chasm_int_to_str(ctx, score));
  chasm_print_s(ctx, msg);
  const char* s = "hello";
  int64_t n = s.len;
  int64_t b = s[0];
  chasm_print(ctx, n);
  chasm_print(ctx, b);
  const char* ch = chasm_str_from_char(ctx, s[0]);
  chasm_print_s(ctx, ch);
  const char* s2 = "  Hello, Chasm!  ";
  chasm_print(ctx, chasm_str_trim(ctx, s2));
  chasm_print(ctx, chasm_str_trim(ctx, s2).lower);
  chasm_print(ctx, chasm_str_contains(ctx, s2, "Chasm"));
  chasm_print(ctx, chasm_str_slice(ctx, s2, 8, 13));
  const char* a = "Hello";
  const char* b2 = ", world";
  chasm_print(ctx, chasm_str_concat(ctx, a, b2));
  chasm_print_s(ctx, chasm_str_concat(ctx, a, b2));
  chasm_print_s(ctx, chasm_int_to_str(ctx, 42));
  chasm_print_s(ctx, chasm_float_to_str(ctx, 3.14));
  chasm_print_s(ctx, chasm_bool_to_str(ctx, true));
  chasm_print_s(ctx, chasm_str_from_char(ctx, 65));
}

